### PR TITLE
A collection of bug fixes

### LINKED ISSUE #3789: Settings not visible
### What happened?

When I enter in user preferences (`http://192.168.1.6:5000/settings#preferences`) not preferences are show. I need to click on `Locale` and then all the preferences are show.

Image

I am using Firefox 138.0.1 on ubuntu 25.10 and Kavita v0.8.6.2 (Docker image)

### What did you expect?

All the preferences settings are shown.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.6.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #3793: Webtoon mode cannot be disabled
### What happened?

Other settings are saved correctly, but only webtoon view mode settings are not disabled normally.

### What did you expect?

https://github.com/user-attachments/assets/2b33ae70-6150-45cc-895c-b2cc3c58d1c2

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.6.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #3806: Chapter Info display is missing the heading for Word Count
### What happened?

Image

In the info display there is just a floating `0 Words` with no heading. 

### What did you expect?

The heading `Word Count` 

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #3808: Reading list more and reorder items buttons do not appear on mobile
### What happened?

more and reorder items buttons do not appear on mobile

### What did you expect?

buttons should appear

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #3810: Search shortcut appears on mobile
### What happened?

Image

### What did you expect?

Search shortcut shouldn't appear on mobile

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #3817: Book reader Table of Contents (still) loses active section
### What happened?

[This issue](https://github.com/Kareadita/Kavita/issues/3473) is still happening with certain EPUBs, where the TOC highlight disappears if I'm not on the first section for a chapter.

### What did you expect?

I would expect Kavita to keep the title of chapter 1 bolded until I reached the beginning of chapter 2. I don't think there should be a case where there is no active chapter.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.6.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell

```

### Additional Notes

I can provide an EPUB to test with if requested.

### LINKED ISSUE #3818: Can't change the password of a non-admin account
### What happened?

Logged in as a non-admin user, if I go to my account settings and try to change my password, I'm simply logged out and my password is not changed.

### What did you expect?

My password should be changed. Not sure if I should be logged out or if I should stay logged in.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.6.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell
[Kavita] [2025-05-17 15:04:43.880 -05:00 109] [Information] API.Controllers.AccountController Manga is changing Manga's password


[Kavita] [2025-05-17 15:04:43.881 -05:00 109] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/account/reset-password responded 401 in 8.7188 ms


[Kavita] [2025-05-17 15:04:43.967 -05:00 253] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/admin/exists responded 200 in 3.2279 ms


[Kavita] [2025-05-17 15:05:06.949 -05:00 253] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/admin/exists responded 200 in 2.5442 ms


[Kavita] [2025-05-17 15:05:12.094 -05:00 109] [Information] API.Controllers.AccountController Manga attempting to login from ::ffff:172.18.0.1


[Kavita] [2025-05-17 15:05:12.156 -05:00 109] [Warning] API.Controllers.AccountController Manga failed to log in at "2025-05-17T15:04:24.0733127": Your credentials are not correct
```

### Additional Notes

_No response_

### LINKED ISSUE #3819: The "Section" and "Page" bars in the Book Reader seem to be confused
### What happened?

The "Section" bar, when hovered, says "Go to page" rather than "Go to section". Also, once clicked, a popup appears asking the user to select a page to go to. This changes the section, not the page, and is off by 1 (entering 1 takes me to section 0, and to go to the last section I had to enter 43).
The "Page" bar cannot be clicked, and doesn't say anything when hovered. 

Image

### What did you expect?

- The section bar should not use "page" in the tooltip or popup.
- The page bar should work similar to the section bar, allowing you to navigate to any page in the section.
- The section popup should take you to the number you entered, i.e., entering 5 should take me to section 5.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.6.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #3830: Specials can't be downloaded on mobile UI
### What happened?

Books under Specials tab don't have download button inside _Others_ on mobile UI.

Image

Image

### What did you expect?

Have download button for books under Specials tab inside _Others_.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by Fesaa**
# Changed
- Changed: Reading lists will now only show one of promote & unpromote
- Changed: Collections will now only show one of promote & unpromote
- Changed: The reset password form will now be disabled if you do not have permissions to change your password (Fixes #3818)
- Changed: The ToC in the EPUB reader will now mark a chapter as current until the next chapter is reached (Fixes #3817)
- Changed: Go to Page prompts on book/manga reader now use a custom styled window
- Changed: Removed the opacity from tooltips

# Fixed
- Fixed: Fixed being unable to disable/enable automatic webtoon detection (Fixes #3793)
- Fixed: Fixed the volume modal missing the word count header (Fixes #3806)
- Fixed: Fixed search shortcut hint appearing on small devices (Fixes #3810) (develop)
- Fixed: Fixed actionables not showing up correctly on mobile (Fixes #3808) (develop)
- Fixed: Fixed preferences not displaying until locale took too long to load in (Fixes #3789)
- Fixed: Fixed the section jumper in the EPUB reader using the wrong terms (Fixes #3819)
- Fixed: Fixed download actionable missing for Admins in some cases 
- Fixed: Fixed missing download handlers on series detail for volume/chapter entities. (Fixes #3830)

### CODE REVIEW

File: UI/Web/src/app/collections/_components/collection-detail/collection-detail.component.ts [hunk 1]
```diff
@@ -225,6 +226,17 @@ export class CollectionDetailComponent implements OnInit, AfterContentChecked {
     });
   }
 
+  shouldRenderCollection(action: ActionItem<UserCollection>, entity: UserCollection, user: User) {
```
Comment (majora2007) [inline UI/Web/src/app/collections/_components/collection-detail/collection-detail.component.ts:229]: These should be named shouldRenderCollectionAction to align with other code signatures

File: UI/Web/src/assets/langs/en.json [hunk 2]
```diff
@@ -882,7 +882,7 @@
         "incognito-mode-label": "Incognito Mode",
         "next": "Next",
         "previous": "Previous",
-        "go-to-page-prompt": "There are {{totalPages}} pages. What page do you want to go to?"
+        "go-to-section-prompt": "There are {{totalSections}} sections. What section do you want to go to?"
```
Comment (majora2007) [inline UI/Web/src/assets/langs/en.json:890]: The code around pages/sections doesn't make sense to me. An epub has pages (the physical pages) and sections for when the reader breaks it into column mode.

Comment (Fesaa) [reply UI/Web/src/assets/langs/en.json:890]: Yes, the naming was also a little confusing to me. I might want to leave an extra comment on the method. 

The changes were for this issue: https://github.com/Kareadita/Kavita/issues/3819; if that clears it up for you?
