### PR TITLE
Ability to turn off Metadata Parsing

### LINKED ISSUE #3834: Episode distinction error due to title
### What happened?

Title : 3회차 인생은 악역 영애로 살겠습니다
Link : https://ridibooks.com/books/840071064

The problem of the volume being designated as 3 volumes due to the part '3회차' in the title.

### What did you expect?

I think we need a feature that allows us to ignore volumes that come after a title that has an episode name at the beginning of the title.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.6.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Other iOS Browser

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #3844: Series not matching from Matched metadata table
### What happened?

When trying to match a series from this table

Image

Image

The UI says the series matched correctly but logs show it hit rate limit and didn't find any match.

I don't think it's actually a rate limit issue because other series not on the table match properly

This happens both on Manga/LN and Comics

### What did you expect?

Either the series to match (since there's actually a match there on the second picture) or to tell me it did fail on the UI

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell
[Kavita] [2025-06-05 10:06:11.128 -03:00  67] [Debug] API.Services.Plus.ExternalMetadataService Fetching Kavita+ Series Detail data for 5 Ronin (2011)

[Kavita] [2025-06-05 10:06:11.317 -03:00  67] [Information] API.Services.Plus.ExternalMetadataService Hit rate limit twice, try again later

[Kavita] [2025-06-05 10:06:11.318 -03:00  67] [Error] API.Services.Plus.ExternalMetadataService Unable to Match 5 Ronin (2011) with Kavita+ Series with Id: 0/0/9921
```

### Additional Notes

_No response_

### LINKED ISSUE #3868: Cannot remove items from a reading list
### What happened?

I have a reading list of comics which I have created manually in a sorted order. I mistakenly added an item that doesn't belong in the list and I would like to remove it from the list.

I click "reorder" on the reading list which allows me to see and manually sort the list of items. I can drag-n-drop them or change their number in the list to resort them. On the tile for each item I can see an 'X' on far right. Clicking on the "X" currently does nothing. 

### What did you expect?

When I click on the "X" I would expect to see the item removed from the list.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.6.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by majora2007**
# Added
- Added: Added a new library setting to disable metadata parsing. This setting, when off, will ensure Kavita only uses filename parsing (Closes FR #3695)

# Changed
- Changed: Carry over incognito between chapter loads (in the url)
- Changed: Throw a toastr on matched metadata page when there is a rate limit issue. (Fixes #3844)

# Fixed
- Fixed: On desktop, don't allow clicking on the genre/tag as issue browsing is not yet implemented (develop)
- Fixed: Removed 회 as a volume parsing marker per request (Fixes #3834 )
- Fixed: Fixed reading list delete button not working (Fixes #3868)

### CODE REVIEW

File: API/DTOs/LibraryDto.cs [hunk 1]
```diff
@@ -65,5 +65,5 @@ public sealed record LibraryDto
     /// </summary>
     /// <remarks>This does not exclude the library from being linked to wrt Series Relationships</remarks>
     /// <remarks>Requires a valid LicenseKey</remarks>
-    public bool AllowMetadataMatching { get; set; } = true;
+    public bool EnableMetadata { get; set; } = true;
```
Comment (Fesaa) [inline API/DTOs/LibraryDto.cs:72]: Is it supposed to replace AllowMetadataMatching? The doc comment isn't updated either

File: API/Services/Plus/ExternalMetadataService.cs [hunk 2]
```diff
@@ -442,16 +439,12 @@ private async Task<SeriesDetailPlusDto> FetchExternalMetadataForSeries(int serie
...
             SeriesDetailPlusApiDto? result = null;
 
             try
             {
-                result = await (Configuration.KavitaPlusApiUrl + "/api/metadata/v2/series-detail")
-                    .WithKavitaPlusHeaders(license, token)
-                    .PostJsonAsync(data)
-                    .ReceiveJson<SeriesDetailPlusApiDto>(); // This returns an AniListSeries and Match returns ExternalSeriesDto
+                // This returns an AniListSeries and Match returns ExternalSeriesDto
+                result = await _kavitaPlusApiService .GetSeriesDetail(data);
```
Comment (Fesaa) [inline API/Services/Plus/ExternalMetadataService.cs]: Space before the method call

**Review by Fesaa — COMMENTED** [review]
Really just that one thing, tbf
Maybe something to remember for when we get to the scanner rewrite could be to use a context instead. So adding a parameter doesn't require changing the signature of 20 methods

**Comment by majora2007** [comment]
> Maybe something to remember for when we get to the scanner rewrite could be to use a context instead. So adding a parameter doesn't require changing the signature of 20 methods

I was thinking the exact same thing when adding it.
