### PR TITLE
A few reading list bug fixes

### LINKED ISSUE #3651: Users unable to access reading lists via OPDS or create reading lists
### What happened?

I created a reading list as an admin user and promoted it, other users are able to view it on the web interface but can't access it via OPDS (406 error). Additionally other users seem to be unable to create reading lists on their own despite having permissions.

To reproduce the error, I created a new user with admin role, permission to full library, and "No Restriction" for Age Rating. With this user if I navigate to the OPDS endpoint for a particular reading list (https://<url>/api/opds/<api_key_new_user>/reading-list/36) in the browser I get a 406 error but if I try to navigate to a series (https://<url>/api/opds/<api_key_new_user>/series/245) I get the XML file back fine.

Accessing the reading list in the browser with my own account (https://<url>/api/opds/<api_key_my_user>/reading-list/36) works fine and returns the XML. With the newly created admin user if I navigate to an Issue on the Kavita frontend and try to create a reading list by "Add to Reading List" I get a 400 Error "You are not permitted to this operation".
Image

### What did you expect?

Other users are able to access reading lists via OPDS and able to create reading lists.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.5.11 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell
[Kavita] [2025-03-17 21:09:02.297 -07:00  64] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/opds/<user_api_key>/reading-list/38 responded 406 in 2.7982 ms

[Kavita] [2025-03-17 21:14:23.393 -07:00  70] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/opds/<user_api_key>/series/245 responded 200 in 107.3252 ms
```

### Additional Notes

docker-compose.yml contents
```yaml
  kavita:
    image: jvmilazz0/kavita:latest    # Using the stable branch from the official dockerhub repo.
    container_name: kavita
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
        - "/data/comics/sorted:/comics"          # location is in a NFS mounted drive
        - "/home/docker_stuff/kavita_config/db:/kavita/config"  
    environment:
        - TZ=America/Los_Angeles
    ports:
        - "5000:5000"
    restart: unless-stopped
```

### LINKED ISSUE #3654: Unnecessary 'Volume' Prefix from Ebook Specials in Reading List
### What happened?

When a ebook special is added to a reading list, the word "Volume" appears in front of the title. It seems unnecessary and can be removed.

I only tested light novel library and epub file. Not sure about other types.

Image

### What did you expect?

The "Volume" prefix should be removed.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by Fesaa**
# Changed
- Changed: Reading lists' age rating will now update when a series age rating is updated via the UI

# Fixed
- Fixed: Fixed 'add to reading list' not working in volume detail
- Fixed: Fixed users being unable to open promoted reading lists via OPDS (Fixes #3651)
- Fixed: Fixed reading lists, adding an unnecessary volume marker for EPUB specials (Fixes #3654)

I'm waiting with it updating age ratings after a library scan till after we've done the scanner rework.

### CODE REVIEW

File: API/Controllers/OPDSController.cs [hunk 1]
```diff
@@ -580,19 +583,23 @@ private static UserParams GetUserParams(int pageNumber)
...
             return BadRequest(await _localizationService.Translate(userId, "opds-disabled"));
-        var (baseUrl, prefix) = await GetPrefix();
+
         var user = await _unitOfWork.UserRepository.GetUserByIdAsync(userId);
+        if (user == null)
+            return Unauthorized();
+
+        var readingLists = await _unitOfWork.ReadingListRepository.GetReadingListDtosForUserAsync(user.Id, true, GetUserParams(pageNumber), false);
+        if (readingLists == null)
+            return Unauthorized();
```
Comment (majora2007) [inline API/Controllers/OPDSController.cs:601]: When you have an if then return, do it on one line, otherwise use {}

File: API/Controllers/OPDSController.cs [hunk 2]
```diff
@@ -580,19 +583,23 @@ private static UserParams GetUserParams(int pageNumber)
...
 
-        var userWithLists = await _unitOfWork.UserRepository.GetUserByUsernameAsync(user!.UserName!, AppUserIncludes.ReadingListsWithItems);
-        if (userWithLists == null) return Unauthorized();
-        var readingList = userWithLists.ReadingLists.SingleOrDefault(t => t.Id == readingListId);
+        var readingList = readingLists.SingleOrDefault(rl => rl.Id == readingListId);
```
Comment (majora2007) [inline API/Controllers/OPDSController.cs]: Use FirstOrDefault instead

File: API/Controllers/OPDSController.cs [hunk 3]
```diff
@@ -580,19 +583,23 @@ private static UserParams GetUserParams(int pageNumber)
...
         if (readingList == null)
-        {
             return BadRequest(await _localizationService.Translate(userId, "reading-list-restricted"));
```
Comment (majora2007) [inline API/Controllers/OPDSController.cs:607]: Same comment about the if statement, since this is long, it makes sense to keep the {}

File: API/Services/ReadingListService.cs [hunk 4]
```diff
@@ -844,4 +858,19 @@ public async Task<string> GenerateReadingListCoverImage(int readingListId)
...
+    {
+        var readingLists = await _unitOfWork.ReadingListRepository.GetReadingListsBySeriesId(seriesId);
+        foreach (var readingList in readingLists)
+        {
+            var seriesIds = readingList.Items.Select(item => item.SeriesId).ToList();
+            seriesIds.Remove(seriesId); // Don't get AgeRating from database
+
+            var maxAgeRating = await _unitOfWork.SeriesRepository.GetMaxAgeRatingFromSeriesAsync(seriesIds);
+            if (ageRating > maxAgeRating)
+                maxAgeRating = ageRating;
```
Comment (majora2007) [inline API/Services/ReadingListService.cs:873]: Use {} since there is no direct control flow jump.

File: API/Services/ReadingListService.cs [hunk 5]
```diff
@@ -844,4 +858,19 @@ public async Task<string> GenerateReadingListCoverImage(int readingListId)
 
         return !_directoryService.FileSystem.File.Exists(destFile) ? string.Empty : destFile;
     }
+    public async Task UpdateReadingListAgeRatingForSeries(int seriesId, AgeRating ageRating)
+    {
+        var readingLists = await _unitOfWork.ReadingListRepository.GetReadingListsBySeriesId(seriesId);
+        foreach (var readingList in readingLists)
+        {
+            var seriesIds = readingList.Items.Select(item => item.SeriesId).ToList();
+            seriesIds.Remove(seriesId); // Don't get AgeRating from database
```
Comment (majora2007) [inline API/Services/ReadingListService.cs:868]: I don't understand the logic here. The method is to update the RL's Age Rating for a given series, but we aren't using that series' age rating in the final calculation...?

Comment (majora2007) [reply API/Services/ReadingListService.cs:868]: Reading further, this method is used in the UI. I think that the signature needs to be updated and documentation added. Also needs to say that it doesn't commit, as you would expect it to.

File: API/Services/ReadingListService.cs [hunk 6]
```diff
@@ -844,4 +858,19 @@ public async Task<string> GenerateReadingListCoverImage(int readingListId)
 
         return !_directoryService.FileSystem.File.Exists(destFile) ? string.Empty : destFile;
     }
+    public async Task UpdateReadingListAgeRatingForSeries(int seriesId, AgeRating ageRating)
```
Comment (majora2007) [inline API/Services/ReadingListService.cs:862]: Newline above method

File: UI/Web/src/app/reading-list/_components/reading-list-item/reading-list-item.component.html [hunk 7]
```diff
@@ -42,7 +42,7 @@ <h5 class="mb-1 pb-0" id="item.id--{{position}}">
 
         @if (item.releaseDate !== '0001-01-01T00:00:00') {
           <div class="ps-1 mt-2">
-            Released: {{item.releaseDate | date:'longDate'}}
+            {{t('released')}}{{item.releaseDate | date:'longDate'}}
```
Comment (majora2007) [inline UI/Web/src/app/reading-list/_components/reading-list-item/reading-list-item.component.html]: You need to update this to be `{{t('released-label', {date: item.releaseDate | date:'longDate'})}}`. 

This is because not all languages are read left to right or even have spaces. Kavita has some norms for localizers on how strings are used based on their key name.

File: UI/Web/src/app/volume-detail/volume-detail.component.ts [hunk 8]
```diff
@@ -613,6 +613,7 @@ export class VolumeDetailComponent implements OnInit {
         });
         break;
       case Action.AddToReadingList:
+        this.actionService.addVolumeToReadingList(this.volume!, this.seriesId, () => {/* No Operation */ });
```
Comment (majora2007) [inline UI/Web/src/app/volume-detail/volume-detail.component.ts]: I believe the callback is nullable, so you should be able to just not pass anything.

**Review by majora2007 — CHANGES_REQUESTED** [review]

File: API/Services/ReadingListService.cs (hunk 5 above)
Comment (Fesaa) [reply API/Services/ReadingListService.cs:868]: The documentation for this method in its definition in the interface at the top of the file. Does mention this.

Since it's being called when we're still in the process of updating the series, the age rating isn't updated in the database yet, so we have to pass it as a parameter. 

And it doesn't commit, as we leave that up to the caller in case it wants to back out of updating later.

**Review by majora2007 — APPROVED** [review]
