### PR TITLE
Issue-4423: restrict the read only user from adjusting settings in the preferences

### LINKED ISSUE #4423: Wrong error code in changing language
### What happened?

On the instance of kavita (https://demo-next.kavitareader.com/) logged into a readonly account (translator) and tried changing the language, i got error 400. There is no message indicating that I lack permissions. 

### What did you expect?

Instead of getting error 400 i expected to get error 403

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by IbrahimHamshari**
# Fixed
- Fixed: Read only accounts can make changes to settings in the UI. (Fixes #4423)

### CODE REVIEW

**Comment by majora2007** [comment]
We usually return a bad request for permission errors

File: UI/Web/src/app/user-settings/manga-user-preferences/manage-user-preferences.component.ts [hunk 1]
```diff
@@ -158,55 +158,77 @@ export class ManageUserPreferencesComponent implements OnInit {
...
+
+         opdsPreferences: this.fb.group({
+           embedProgressIndicator: this.fb.control<boolean>(pref.opdsPreferences.embedProgressIndicator),
+           includeContinueFrom: this.fb.control<boolean>(pref.opdsPreferences.includeContinueFrom),
+         })
+       });
+
+        // Disable entire form for readonly users (all controls, recursively, without emitting events)
+        if (this.accountService.isReadOnly()) {
+          var disableRecursive = (ctrl: any) => {
```
Comment (Fesaa) [inline UI/Web/src/app/user-settings/manga-user-preferences/manage-user-preferences.component.ts]: Angular disables children when disabling a FormGroup or FormArray. This isn't needed

**Review by Fesaa — CHANGES_REQUESTED** [review]

File: UI/Web/src/app/user-settings/manga-user-preferences/manage-user-preferences.component.ts (hunk 1 above)
Comment (IbrahimHamshari) [reply UI/Web/src/app/user-settings/manga-user-preferences/manage-user-preferences.component.ts]: Updated.

**Comment by IbrahimHamshari** [comment]
Just to note. This was done with the help of the AI since I don't know much about angular. I originally thought I will be changing the BE to return 403 and get to know more about the permission subsystem that is used here lol.

File: UI/Web/src/app/settings/_components/setting-key-bind-picker/setting-key-bind-picker.component.html
Comment (Fesaa) [inline UI/Web/src/app/settings/_components/setting-key-bind-picker/setting-key-bind-picker.component.html:1]: Please add [disabled]="accountService.isReadOnly()" to the add & reset buttons to indicate they cannot be used

File: UI/Web/src/app/user-settings/manga-user-preferences/manage-user-preferences.component.ts [hunk 2]
```diff
@@ -158,55 +158,66 @@ export class ManageUserPreferencesComponent implements OnInit {
...
+           shareProfile: this.fb.control<boolean>(pref.socialPreferences.shareProfile),
+         }),
+
+         opdsPreferences: this.fb.group({
+           embedProgressIndicator: this.fb.control<boolean>(pref.opdsPreferences.embedProgressIndicator),
+           includeContinueFrom: this.fb.control<boolean>(pref.opdsPreferences.includeContinueFrom),
+         })
+       });
+
+        // Disable entire form for readonly users
```
Comment (Fesaa) [inline UI/Web/src/app/user-settings/manga-user-preferences/manage-user-preferences.component.ts]: Can we remove comments that are explained by reading code

**Review by Fesaa — CHANGES_REQUESTED** [review]
Changing the http code is out of scope for this PR, and would not some more thought, as we'd need to make sure it's handled correctly everywhere. I'm personally for it, it'd be good to leverage the codes correctly. But it's not the most needed change.

Thanks for the changes, and the PR. I pulled down now and have a few more comments

You'll need to go over the manage-user-preferences form and add the appropriate disabled (or canEdit for app-settings-items) attribute to a few more controls as they're manual. 

- Dropdowns
- Highlights colour picker
- social libraries typeahead
- re-read prompt

File: UI/Web/src/app/user-settings/manga-user-preferences/manage-user-preferences.component.ts [hunk 3]
```diff
@@ -158,55 +158,62 @@ export class ManageUserPreferencesComponent implements OnInit {
...
-          return this.accountService.updatePreferences(data);
-        }),
-        tap(prefs => {
-          if (this.user) {
-            this.user.preferences = {...prefs};
-            this.cdRef.markForCheck();
-          }
-        })
-      ).subscribe();
+       this.settingsForm = this.fb.group({
```
Comment (majora2007) [inline UI/Web/src/app/user-settings/manga-user-preferences/manage-user-preferences.component.ts]: Your code seems to be indented slightly making the diff hard to read. Can you revert this?

**Comment by majora2007** [comment]
Please pull develop in (for the slight conflict on accountService), otherwise it looks good from a code standpoint. I can test this out shortly.

**Comment by Fesaa** [comment]
Thank you for the contribution, we'll release this with the next nightly! ❤️
