### PR TITLE
Versioning Fix & Improvement

### LINKED ISSUE #544: Changelog view is showing the latest version as installed even if you're behind a version
Be on version v0.4.4 and have v0.4.5 out, the v0.4.5 will show as installed.

### PR DESCRIPTION
**Pull request by Inpacchi**
# Added
* Added: "Available" now displays on all newer, uninstalled updates

# Fixed
* Fixed: The changelog now shows the correct version currently installed, as well as any versions available for update

Fixes #544

### CODE REVIEW

File: API/Services/Tasks/VersionUpdaterService.cs [hunk 1]
```diff
@@ -90,12 +90,14 @@ public async Task<IEnumerable<UpdateNotificationDto>> GetAllReleases()
         private UpdateNotificationDto CreateDto(GithubReleaseMetadata update)
         {
             if (update == null || string.IsNullOrEmpty(update.Tag_Name)) return null;
-            var version = update.Tag_Name.Replace("v", string.Empty);
-            var updateVersion = new Version(version);
+            var updateVersion = new Version(update.Tag_Name.Replace("v", string.Empty));
+            var currentVersion = updateVersion.Revision == -1
+                ? BuildInfo.Version.ToString().Substring(0, 5)
```
Comment (majora2007) [inline API/Services/Tasks/VersionUpdaterService.cs:95]: Don't substring as if we have 0.10.1.1, it will break. If anything, you can substring(0, BuildInfo.Version.ToString().LastIndexOf("."))

but move the BuildInfo.Version.ToString() to a local variable.

File: UI/Web/src/app/admin/changelog/changelog.component.html [hunk 2]
```diff
@@ -1,7 +1,10 @@
 <ng-container *ngFor="let update of updates; let indx = index;">
     <div class="card w-100 mb-2" style="width: 18rem;">
         <div class="card-body">
-          <h5 class="card-title">{{update.updateTitle}}&nbsp;<span class="badge badge-secondary" *ngIf="update.updateVersion === update.currentVersion">Installed</span></h5>
+          <h5 class="card-title">{{update.updateTitle}}&nbsp;
+              <span class="badge badge-secondary" *ngIf="update.updateVersion <= update.currentVersion">Installed</span>
```
Comment (majora2007) [inline UI/Web/src/app/admin/changelog/changelog.component.html:5]: We can use an else statement on the ngIf to avoid potential bugs and duplicate logic.
```
*ngIf="update.updateVersion <= update.currentVersion; else available"
<ng-template #available>
 <span class="badge badge-secondary">Available</span>
          </h5>
</ng-template>
```

**Review by majora2007 — CHANGES_REQUESTED** [review]
Please update the PR Body and the following comments.

File: UI/Web/src/app/admin/changelog/changelog.component.html (hunk 2 above)
Comment (Inpacchi) [reply UI/Web/src/app/admin/changelog/changelog.component.html]: Didn't realize if...else logic was available in Angular templating. That's pretty awesome and good to know. Made the change.

File: API/Services/Tasks/VersionUpdaterService.cs (hunk 1 above)
Comment (Inpacchi) [reply API/Services/Tasks/VersionUpdaterService.cs]: Duh, don't know how I didn't think of that. Made the change.

**Comment by Inpacchi** [comment]
PR body updated.

File: API/Services/Tasks/VersionUpdaterService.cs [hunk 3]
```diff
@@ -90,12 +90,18 @@ public async Task<IEnumerable<UpdateNotificationDto>> GetAllReleases()
...
         {
             if (update == null || string.IsNullOrEmpty(update.Tag_Name)) return null;
-            var version = update.Tag_Name.Replace("v", string.Empty);
-            var updateVersion = new Version(version);
+            var updateVersion = new Version(update.Tag_Name.Replace("v", string.Empty));
+            var currentVersion = BuildInfo.Version.ToString();
+
+            if (updateVersion.Revision == -1)
+            {
+                currentVersion = BuildInfo.Version.ToString()
```
Comment (majora2007) [inline API/Services/Tasks/VersionUpdaterService.cs:98]: cache this into a variable to avoid duplicate string creations

Comment (Inpacchi) [reply API/Services/Tasks/VersionUpdaterService.cs:98]: So you mean instead of modifying the currentVersion variable, create a new variable?

Comment (majora2007) [reply API/Services/Tasks/VersionUpdaterService.cs:98]: No, I mean just cache the BuildInfo.Version.ToString() then use that in the following lines of code. 

Essentially, just want to avoid 2 string creations.

Comment (Inpacchi) [reply API/Services/Tasks/VersionUpdaterService.cs:98]: Ah, I understand now. Got it!

File: API/Services/Tasks/VersionUpdaterService.cs [hunk 4]
```diff
@@ -90,12 +90,19 @@ public async Task<IEnumerable<UpdateNotificationDto>> GetAllReleases()
...
             if (update == null || string.IsNullOrEmpty(update.Tag_Name)) return null;
-            var version = update.Tag_Name.Replace("v", string.Empty);
-            var updateVersion = new Version(version);
+            var buildVersion = BuildInfo.Version;
+            var updateVersion = new Version(update.Tag_Name.Replace("v", string.Empty));
+            var currentVersion = buildVersion.ToString();
+
+            if (updateVersion.Revision == -1)
+            {
+                currentVersion = buildVersion.ToString()
```
Comment (majora2007) [inline API/Services/Tasks/VersionUpdaterService.cs:99]: You're close, so it's like this:
```
var currentVersion = buildVersion.ToString();
currentVersion = currentVersion .SubString(0, buildVersion.LastIndexOf("."))
```
You don't want to keep calling toString because it keeps creating a temp string.

Comment (Inpacchi) [reply API/Services/Tasks/VersionUpdaterService.cs:99]: Ah, okay. Sorry, still brushing up on my C#. Python has spoiled me, lol.

**Review by majora2007 — APPROVED** [review]
