### PR TITLE
Koreader Sync Fix and More

### LINKED ISSUE #3910: Koreader sync not working on a particular book
### What happened?

1. Did a force rescan once I updated to 0.8.7 (linux server docker image from ghcr.io)
2. Added OPDS and succesfully downloaded `The Daily Stoic` book
3. Opened it on koreader.
4. Added the sync custom server and logged in succesfully
5. Pushed to sync server
6. Was able to see it from Kavita with a page level precision.
7. I can´t sync down the other way, it says `No progress found for this document`

Then I did the same for `I, Robot`.

I was page 2 on my tablet, and saw a 40% on Kavita... When opening it, it was on the introduction.

Whatever page I went to on the tablet, and then pushed change. It would always come by as 40% progress and open on the introduction on Kavita.

### What did you expect?

I, Robot should work as well as my other book.

The only notable difference is the non-existing TOC on this book. But I got told on Discord it shouldn't matter.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.7 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

Asked for it on discord and [got told to create](https://discord.com/channels/821879810934439936/840693141082341406/1392256380400046230) an issue here

Using `Document matching method` = `binary` and it works fine with other books.

Pulling progress from other device is not working, it says there is none. But It syncs up to kavita properly.

### LINKED ISSUE #3914: Library has Enable Metadata off but still won't parse with "old school" file name method
### What happened?

My library has "Enable Metadata Off", in theory it should be parsing my files by filename (which currently has them all tagged with SPXX in front of the file name for easy sorting). However, nothing is getting updated to reflect my new entries (SP8 and a duplicate attempt at SP9) in my  collection

I do have a second library (used for comics) where I have the metadata ennabled, not sure if that is relevant or not

Image

Image

Image

### What did you expect?

I would have imagined to see the SP8  and SP9 files showing in the collection

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.7 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #3966: Receiving simple error only when running "Analyze Files" on a library
### What happened?

When I try to run an "Analyze Files" call from the UI on a library, I see a red box in the lower right of the screen that says "Something unexpected went wrong" and I do not see any further indicators either in the UI or in the logs of what the error was or if analysis continued beyond the error. 

I bumped the log level to trace and tried it again but didn't see anything more than before in the logs. Only the call to run the analyze process but nothing afterward.

> [Kavita] [2025-07-30 08:48:29.174 -05:00  76] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/library/analyze?libraryId=2 responded 200 in 0.9388 ms

### What did you expect?

I am new to Kavita so I am not sure what to expect but if the process is similar to onboarding a library then I would have expected the status indicator at the top right of the window to show activity and if there were issues then something recorded in the log and/or an entry shown in the media issues section of the admin panel.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.7 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell
[Kavita] [2025-07-30 08:48:29.174 -05:00  76] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/library/analyze?libraryId=2 responded 200 in 0.9388 ms
```

### Additional Notes

I am running Kavita in unraid installed using the linuxserver repository from CA.

### LINKED ISSUE #3970: Reader auto skips to next chapter in webtoon mode
### What happened?

When opening a chapter or volume that is marked as read in webtoon mode, the reader automatically scrolls to the bottom and then skips to the next chapter. If the next chapter is also marked as read, this continues endlessly, though it sometimes stops on certain chapters.

This issue is pretty much 100% reproducible for me on iOS in Safari, on Android in Google Chrome, and on macOS in Safari when Responsive Design Mode is enabled and set to a device like the iPhone Pro Max. I cannot reproduce this behavior using Safari in normal mode on macOS, though it did happen a few rare times during testing.

Steps to reproduce:
1. Open any cbz format chapter that is marked as read in webtoon mode (happens on both webtoons with long images and mangas)
2. Observe automatic scrolling and skipping to next chapter

As requested in Discord the screen recording demonstrating the issue: https://youtu.be/qMRak_ttheM

### What did you expect?

The reader not automatically skipping to the next volume/chapter.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.7 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Mac

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Safari

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #3989: Mal Stack option missing under import menu
### What happened?

The MAL Stack option isn't showing up for some users in the server settings page. 

Image

### What did you expect?

Spot to manage MAL stacks 

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.7 - Stable

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #3991: [Stable & Nightly] Bulk Actions not hooked up
### What happened?

When selecting bulk actions in the Libraries screen of the settings there's no response on the dev console indicating they're not actually hooked up to their intended functions.

This was reported on discord by jncmoney on stable and verified by me as present still in nightly.

### What did you expect?

Bulk actions to initiate the expected action when pressed.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Other (List in "Additional Notes" box)

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

All browsers affected

### LINKED ISSUE #3992: Problem with searching for comics with short titles
### What happened?

When searching for a short title, if there are many comics with that short title, the search will not work.

Image

### What did you expect?

This issue occurs when searching directly in the library, but when searching for a title in the top search, it fails to appear if there are many overlapping titles.

Image

Regarding this issue, we need to improve the search so that when a search hits a 100% score, the title appears at the top. Alternatively, instead of being hidden after a certain number of searches, the title can be viewed using the More button.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.7 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Other iOS Browser

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #4000: API - Pagination on endpoint api/Opds/{apiKey}/recently-updated is not possible
Hello,

It seems that the _pageNumber_ parameter in method _GetRecentlyUpdated_ isn't used, therefor it is not possible to access page 2
https://github.com/Kareadita/Kavita/blob/aa268c2dcaae9178bf1c4119b152f424181f6fd7/API/Controllers/OPDSController.cs#L722C88-L722C99

I'm trying to get all series that were updated in the last week. I might have more than 20.

Could you fix this endpoint, or is there another way for me to do that?

I already tried the api/Series/recently-updated-series but no dice, it is also limited to 20 items and no pagination is available.

Thank you.

### PR DESCRIPTION
**Pull request by Fesaa**
# Added
- Added: Added support for pagination in the Recently updated endpoint (OPDS and normal) (Closes #4000)

# Changed
- Changed: Remove mentions of the analyze library option in the UI (Closes #3966)
- Changed: Search results will now be sorted by length first to ensure short titles are always findable (Closes #3992)
- Changed: Added an additional check to Manga volume/chapter parser to handle duplicate volume/chapter markers in the file:
'Series - Vol 1 Ch 2.5 - Vol 2 Omakes'
This will now be parsed correctly as Volume 1 Chapter 2.5.

# Fixed
- Fixed: Fixed side nav not being removed when library access is removed during login with OIDC (develop)
- Fixed: Fixed id_token missing when being redirected after a restart (develop)
- Fixed: Fixed MAL import section missing from settings (develop) (Fixes #3989)
- Fixed: Fixed bulk actions not being hooked up on the libraries settings page (Fixes #3991)
- Fixed: Fixed some internal metadata still being used when Enable Metadata is turned off (Fixes #3914)
- Fixed: Try to fix webtoon reader skipping chapters when opening fully read chapters (Maybe fixes #3970)
- Fixed: Fixed an issue where Koreader was not able to pull progress from Kavita (Fixes #3910)

### CODE REVIEW

File: API/Controllers/OPDSController.cs [hunk 1]
```diff
@@ -723,11 +723,19 @@ public async Task<IActionResult> GetRecentlyUpdated(string apiKey, [FromQuery] i
     {
         var userId = await GetUser(apiKey);
         if (!(await _unitOfWork.SettingsRepository.GetSettingsDtoAsync()).EnableOpds)
+        {
             return BadRequest(await _localizationService.Translate(userId, "opds-disabled"));
```
Comment (majora2007) [inline API/Controllers/OPDSController.cs:761]: It might be nice to move these checks into the middleware for this route, so we aren't repeating ourselves constantly.

File: API/Data/Repositories/SeriesRepository.cs [hunk 2]
```diff
@@ -134,7 +134,7 @@ public interface ISeriesRepository
     Task<Series?> GetFullSeriesForSeriesIdAsync(int seriesId);
     Task<Chunk> GetChunkInfo(int libraryId = 0);
     Task<IList<SeriesMetadata>> GetSeriesMetadataForIdsAsync(IEnumerable<int> seriesIds);
-    Task<IEnumerable<GroupedSeriesDto>> GetRecentlyUpdatedSeries(int userId, int pageSize = 30);
+    Task<IEnumerable<GroupedSeriesDto>> GetRecentlyUpdatedSeries(int userId, UserParams userParams);
```
Comment (majora2007) [inline API/Data/Repositories/SeriesRepository.cs]: This should be nullable

File: API/Data/Repositories/SeriesRepository.cs [hunk 3]
```diff
@@ -417,7 +417,8 @@ public async Task<SearchResultGroupDto> SearchSeries(int userId, bool isAdmin, I
             .Include(s => s.Library)
             .AsNoTracking()
             .AsSplitQuery()
-            .OrderBy(s => s.SortName!.ToLower())
+            .OrderBy(s => s.SortName.Length)
```
Comment (majora2007) [inline API/Data/Repositories/SeriesRepository.cs]: Sort name can sometimes be null.

File: API/Data/Repositories/SeriesRepository.cs [hunk 4]
```diff
@@ -1490,20 +1492,32 @@ public async Task<IEnumerable<GroupedSeriesDto>> GetRecentlyUpdatedSeries(int us
...
+        var skipped = new HashSet<string>();
+
         foreach (var item in items)
         {
-            if (seriesMap.Keys.Count == pageSize) break;
+            if (seriesMap.Keys.Count == userParams.PageSize) break;
 
             if (item.SeriesName == null) continue;
 
+            var key = item.SeriesName + "_" + item.LibraryId;
```
Comment (majora2007) [inline API/Data/Repositories/SeriesRepository.cs]: Rewrite  this to use $"" string. It's faster and this code is hit a lot (and already quite expensive)

File: API/Data/Repositories/SeriesRepository.cs [hunk 5]
```diff
@@ -1490,20 +1492,32 @@ public async Task<IEnumerable<GroupedSeriesDto>> GetRecentlyUpdatedSeries(int us
...
+
+            if (skipped.Count < toSkip)
+            {
+                skipped.Add(key);
+                continue;
```
[the remark this answers is not in the document]
Comment (majora2007) [reply API/Data/Repositories/SeriesRepository.cs]: Agreed

File: UI/Web/src/app/sidenav/preference-nav/preference-nav.component.html [hunk 6]
```diff
@@ -1,19 +1,21 @@
...
-            @if (hasAnyChildren(user, section)) {
+            @let children = getVisibleChildren(user, section);
+
+            @if (children.length > 0) {
               <h5 class="side-nav-header mb-2" [ngClass]="{'mt-4': idx > 0}">{{t(section.title)}}</h5>
-              @for(item of section.children; track item.fragment) {
-                @if (accountService.hasAnyRole(user, item.roles, item.restrictRoles)) {
-                  <app-side-nav-item [id]="'nav-item-' + item.fragment" [noIcon]="true" link="/settings" [fragment]="item.fragment" [title]="item.fragment | settingFragment" [badgeCount]="item.badgeCount$ | async"></app-side-nav-item>
-                }
+              @for(item of children; track item.fragment) {
```
Comment (majora2007) [inline UI/Web/src/app/sidenav/preference-nav/preference-nav.component.html:17]: You're missing the hasRole check

**Review by majora2007 — CHANGES_REQUESTED** [review]

File: API/Data/Repositories/SeriesRepository.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (Fesaa) [reply API/Data/Repositories/SeriesRepository.cs]: A HashSet doesn't have duplicated items, it's fine to always add them.

We also require to always skip, not only when we haven't seen the series yet. As we want to skip an amount of series, rather than chapters

File: API/Data/Repositories/SeriesRepository.cs (hunk 4 above)
Comment (Fesaa) [reply API/Data/Repositories/SeriesRepository.cs]: This key isn't returned anywhere, only used to track which series have been added to the map already. I've just switched to using the series id

File: API/Data/Repositories/SeriesRepository.cs (hunk 3 above)
Comment (Fesaa) [reply API/Data/Repositories/SeriesRepository.cs]: Is a ! safe then? Or should it rather be `s.SortName?.Length ?? 0` (And variants for the rest).

The type isn't nullable, is this just old code, or might it have been nullable before, and now it can't be? Although, nothing wrong with playing it safe here.

Comment (majora2007) [reply API/Data/Repositories/SeriesRepository.cs]: Nullish should translate fine and it's old code. Actually, it might always be an empty string. Double check in the scan loop for me.

File: UI/Web/src/app/sidenav/preference-nav/preference-nav.component.html (hunk 6 above)
Comment (Fesaa) [reply UI/Web/src/app/sidenav/preference-nav/preference-nav.component.html:17]: The getVisibleChildren method called earlier does the filtering, so we do not need to filter in the html template directly

File: API/Controllers/OPDSController.cs [hunk 7]
```diff
@@ -28,14 +29,57 @@
...
+/**
+ * Middleware that checks if Opds has been enabled for this server
+ */
+[AttributeUsage(AttributeTargets.Class)]
+public class OpdsActionFilterAttribute(IUnitOfWork unitOfWork, ILocalizationService localizationService): ActionFilterAttribute
+{
+
+    public override async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
+    {
+        if (!context.ActionArguments.TryGetValue("apiKey", out var apiKeyObj) ||
```
Comment (majora2007) [inline API/Controllers/OPDSController.cs]: Let's try/catch this whole thing so that in all cases, we can at least return a proper response to the client.

File: API/Controllers/OPDSController.cs [hunk 8]
```diff
@@ -107,10 +152,7 @@ public OpdsController(IUnitOfWork unitOfWork, IDownloadService downloadService,
     [Produces("application/xml")]
     public async Task<IActionResult> Get(string apiKey)
     {
-        var userId = await GetUser(apiKey);
-        if (!(await _unitOfWork.SettingsRepository.GetSettingsDtoAsync()).EnableOpds)
-            return BadRequest(await _localizationService.Translate(userId, "opds-disabled"));
-
+        var userId = (int)HttpContext.Items[UserId]!;
```
Comment (majora2007) [inline API/Controllers/OPDSController.cs]: Refactor this into a method or a getter so that we aren't duplicating code. I also like a space after the cast.
