### PR TITLE
Amelia's Bugs

### LINKED ISSUE #2694: Tap pagination causes issues with text selection (epub) (android)
### What happened?

With tap pagination enabled, selecting text at the edges of a page causes the page to jump to the beginning of the chapter, and what seems like the entire chapter is selcted. Selecting text somewhere in the middle of the page works fine. This issue mostly arises when I attempt to select a word so I can use the context-menu dictionary lookup on my ereader.

### What did you expect?

I expect to be able to select text that I can see on the page, without tap pagination affecting this.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.13 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
N/A
```

### Additional Notes

I suspect this could be fixed in css by setting the left/right floating sections to `user-select: none;` [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select)

### LINKED ISSUE #3588: TitleSort is used as SeriesSort even SeriesSort is set
### What happened?

If `SeriesSort` and `TitleSort` is set, then `TitleSort` is used for series sort.

```xml
<?xml version='1.0' encoding='utf-8'?>
<ComicInfo>
  <Series>Series</Series>
  <SeriesSort>SeriesSort</SeriesSort>
  <TitleSort>TitleSort</TitleSort>
  <Title>Title</Title>
  <Summary>Summary</Summary>
  <Number>1</Number>
  <Year>2025</Year>
  <Month>1</Month>
  <Day>1</Day>
  <LanguageISO>ja</LanguageISO>
</ComicInfo>
```

https://github.com/Kareadita/Kavita/blob/79b4487206e09f61b3b7ca8d36e415e519fc78a6/API/Services/Tasks/Scanner/Parser/DefaultParser.cs#L132-L136

https://github.com/Kareadita/Kavita/blob/79b4487206e09f61b3b7ca8d36e415e519fc78a6/API/Services/Tasks/Scanner/Parser/DefaultParser.cs#L132-L136

### What did you expect?

If `SeriesSort` and `TitleSort` is set, then `SeriesSort` is used  for series sort.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.4.2 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #3609: Impossible to select text without changing page (epub)
### What happened?

Even with tap navigation disabled. Every time you start selecting, the page slides halfway, showing half of the next page. Some pages if I keep trying hard enough it works. So, pretty inconsistent.

### What did you expect?

For it to let me select text, pretty basic feature of a reader.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.5 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell

```

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by majora2007**
# Added
- Added: Ability to delete Smart filter steams from Customize Side Nav and Dashboard
- Added: Ability to rename Smart Filters in Customize settings

# Fixed
- Fixed: Fixed issues with selection on mobile devices in the epub reader causing pages to skip (Fixes #3609, Fixes #2694)
- Fixed: Fixed TitleSort being used instead of SeriesSort for Series Sort field (Fixes #3588) (Thanks @joshuaavalon for the help)
- Fixed: Moved loading icon up so it's visible even when having a lot of cards on library detail page

There are changes around ability to drag and drop to reorder side nav that will be hidden from users until it's polished in this PR.

### CODE REVIEW

File: API/Controllers/FilterController.cs [hunk 1]
```diff
@@ -120,4 +122,39 @@ public ActionResult<FilterV2Dto> DecodeFilter(DecodeFilterDto dto)
...
+        if (user == null) return Unauthorized();
+
+        if (User.IsInRole(PolicyConstants.ReadOnlyRole))
+        {
+            return BadRequest(await _localizationService.Translate(User.GetUserId(), "permission-denied"));
+        }
+
+        if (string.IsNullOrWhiteSpace(name))
+        {
+            return BadRequest("Name must be set");
```
Comment (majora2007) [inline API/Controllers/FilterController.cs]: I will take care of these comments in my branch, but any error like this needs to be localized.

File: API/Controllers/FilterController.cs [hunk 2]
```diff
@@ -120,4 +122,39 @@ public ActionResult<FilterV2Dto> DecodeFilter(DecodeFilterDto dto)
...
+            return BadRequest("You cannot use the name of a system provided stream");
+        }
+
+        var filter = user.SmartFilters.FirstOrDefault(f => f.Id == filterId);
+        if (filter == null)
+        {
+            return BadRequest(await _localizationService.Translate(User.GetUserId(), "filter-not-found"));
+        }
+
+        filter.Name = name.Trim();
```
Comment (majora2007) [inline API/Controllers/FilterController.cs]: You are modifying name here but comparing it against the Default Streams, you would need to trim it on the first line.

File: API/Controllers/StreamController.cs [hunk 3]
```diff
@@ -204,4 +204,20 @@ public async Task<ActionResult> BulkUpdateSideNavStream(BulkUpdateSideNavStreamV
         await _streamService.UpdateSideNavStreamBulk(User.GetUserId(), dto);
         return Ok();
     }
+
+    [HttpPost("delete-smart-filter-side-nav-stream")]
```
Comment (majora2007) [inline API/Controllers/StreamController.cs]: Use HttpDelete in the future

File: API/Data/Repositories/UserRepository.cs [hunk 4]
```diff
@@ -92,9 +92,11 @@ public interface IUserRepository
     Task<IList<DashboardStreamDto>> GetDashboardStreams(int userId, bool visibleOnly = false);
     Task<IList<AppUserDashboardStream>> GetAllDashboardStreams();
     Task<AppUserDashboardStream?> GetDashboardStream(int streamId);
+    Task<AppUserDashboardStream?> GetDashboardStreamWithUser(int streamId);
```
Comment (majora2007) [inline API/Data/Repositories/UserRepository.cs]: You should use a SideNavIncludes pattern instead to allow one method to handle the extra join seemlessly.

File: API/Services/StreamService.cs [hunk 5]
```diff
@@ -344,4 +349,57 @@ public async Task DeleteExternalSource(int userId, int externalSourceId)
 
         await _unitOfWork.CommitAsync();
     }
+
+    public async Task DeleteSideNavSmartFilterStream(int userId, int sideNavStreamId)
+    {
+        var streams2 = await _unitOfWork.UserRepository.GetSideNavStreamWithUser(sideNavStreamId);
```
Comment (majora2007) [inline API/Services/StreamService.cs]: Bad naming

File: API/Services/StreamService.cs [hunk 6]
```diff
@@ -344,4 +349,57 @@ public async Task DeleteExternalSource(int userId, int externalSourceId)
...
+
+        if (streams2.AppUser.Id != userId) throw new KavitaException("sidenav-stream-doesnt-exist");
+
+
+        if (streams2.StreamType != SideNavStreamType.SmartFilter)
+        {
+            throw new KavitaException("sidenav-stream-only-delete-smart-filter");
+        }
+
+        _unitOfWork.UserRepository.Delete([streams2]);
```
Comment (majora2007) [inline API/Services/StreamService.cs]: Add a new method to handle a single item, to avoid an array allocation

File: API/Services/StreamService.cs [hunk 7]
```diff
@@ -344,4 +349,57 @@ public async Task DeleteExternalSource(int userId, int externalSourceId)
...
+    }
+
+    public async Task DeleteDashboardSmartFilterStream(int userId, int dashboardStreamId)
+    {
+        var streams2 = await _unitOfWork.UserRepository.GetDashboardStreamWithUser(dashboardStreamId);
+        if (streams2 == null) throw new KavitaException("dashboard-stream-doesnt-exist");
+
+        if (streams2.AppUser.Id != userId) throw new KavitaException("sidenav-stream-doesnt-exist");
+
+        if (streams2.StreamType != DashboardStreamType.SmartFilter)
```
Comment (majora2007) [inline API/Services/StreamService.cs]: I'm wondering why we need to have 2 different methods and we can't just handle in one DeleteSmartFilter method?

File: API/Services/StreamService.cs [hunk 8]
```diff
@@ -344,4 +349,57 @@ public async Task DeleteExternalSource(int userId, int externalSourceId)
...
+
+        _unitOfWork.UserRepository.Delete([streams2]);
+
+        await _unitOfWork.CommitAsync();
+    }
+
+    public async Task DeleteDashboardSmartFilterStream(int userId, int dashboardStreamId)
+    {
+        var streams2 = await _unitOfWork.UserRepository.GetDashboardStreamWithUser(dashboardStreamId);
+        if (streams2 == null) throw new KavitaException("dashboard-stream-doesnt-exist");
```
Comment (majora2007) [inline API/Services/StreamService.cs]: We need a try/catch around this.

File: UI/Web/src/app/sidenav/_components/customize-sidenav-streams/customize-sidenav-streams.component.ts [hunk 9]
```diff
@@ -148,15 +149,20 @@ export class CustomizeSidenavStreamsComponent implements OnDestroy {
...
 
       const existingExternalSourceStreams = new Set(results[0].filter(d => !d.isProvided && d.streamType === SideNavStreamType.ExternalSource).map(d => d.name));
       this.externalSources = results[2].filter(d => !existingExternalSourceStreams.has(d.name));
       this.cdRef.markForCheck();
     });
   }
 
+  updateSmartFilters() {
+    const existingSmartFilterStreams = new Set(this.items.filter(d => !d.isProvided && d.streamType === SideNavStreamType.SmartFilter).map(d => d.name));
+    this.smartFilters = this.allSmartFilters.filter(d => !existingSmartFilterStreams.has(d.name));
```
Comment (majora2007) [inline UI/Web/src/app/sidenav/_components/customize-sidenav-streams/customize-sidenav-streams.component.ts:163]: This needs a cdRef.markForCheck()

File: UI/Web/src/app/sidenav/_components/dashboard-stream-list-item/dashboard-stream-list-item.component.html [hunk 10]
```diff
@@ -14,6 +14,10 @@ <h5 class="mb-1 pb-0" id="item.id--{{position}}">
               <i class="me-1" [ngClass]="{'fas fa-eye': item.visible, 'fa-solid fa-eye-slash': !item.visible}" aria-hidden="true"></i>
               <span class="visually-hidden">{{t('remove')}}</span>
             </button>
+          <button *ngIf="item.streamType===StreamType.SmartFilter" class="btn btn-icon" (click)="delete.emit(item)">
```
Comment (majora2007) [inline UI/Web/src/app/sidenav/_components/dashboard-stream-list-item/dashboard-stream-list-item.component.html]: Don't use ngIf, use `@if` control flow syntax

File: UI/Web/src/app/sidenav/_components/dashboard-stream-list-item/dashboard-stream-list-item.component.html [hunk 11]
```diff
@@ -14,6 +14,10 @@ <h5 class="mb-1 pb-0" id="item.id--{{position}}">
...
+          <i class="fa-solid fa-trash" aria-hidden="true"></i>
+          <span class="visually-hidden">{{t('delete')}}</span>
```
Comment (majora2007) [inline UI/Web/src/app/sidenav/_components/dashboard-stream-list-item/dashboard-stream-list-item.component.html]: You're missing this localization

File: UI/Web/src/app/sidenav/_components/edit-smart-filter-modal/edit-smart-filter-modal.component.html [hunk 12]
```diff
@@ -0,0 +1,39 @@
+<ng-container *transloco="let t; read:'manage-smart-filters'">
```
Comment (majora2007) [inline UI/Web/src/app/sidenav/_components/edit-smart-filter-modal/edit-smart-filter-modal.component.html:1]: The scope should be the same as the filename, so edit-smart-filter-modal

File: UI/Web/src/app/sidenav/_components/edit-smart-filter-modal/edit-smart-filter-modal.component.ts [hunk 13]
```diff
@@ -0,0 +1,83 @@
...
+
+        if (!exists || isThisSmartFilter) {
+          if (!empty) {
+            this.smartFilterForm.get('name')!.setErrors(null);
+          }
+        } else {
+          this.smartFilterForm.get('name')!.setErrors({duplicateName: true});
+        }
+
+        this.cdRef.detectChanges();
```
Comment (majora2007) [inline UI/Web/src/app/sidenav/_components/edit-smart-filter-modal/edit-smart-filter-modal.component.ts]: Use markForCheck over detectChanges.

File: UI/Web/src/app/sidenav/_components/side-nav/side-nav.component.ts [hunk 14]
```diff
@@ -208,14 +229,31 @@ export class SideNavComponent implements OnInit {
     this.navService.toggleSideNav();
   }
 
-  showMore() {
+  showMore(edit: boolean = false) {
     this.showAllSubject.next(true);
+    this.edit = edit;
```
Comment (majora2007) [inline UI/Web/src/app/sidenav/_components/side-nav/side-nav.component.ts:227]: This needs a cdRef.markForCheck

File: UI/Web/src/app/sidenav/_components/side-nav/side-nav.component.ts [hunk 15]
```diff
@@ -208,14 +229,31 @@ export class SideNavComponent implements OnInit {
...
     this.filterQuery = '';
     this.cdRef.markForCheck();
     this.showAllSubject.next(false);
+    this.edit = false;
+  }
+
+  async drop($event: CdkDragDrop<any, any, SideNavStream>) {
+    const stream = $event.item.data;
+    // Offset the home, back, and customize button
+    this.navService.updateSideNavStreamPosition(stream.name, stream.id, stream.order, $event.currentIndex-3).subscribe({
```
Comment (majora2007) [inline UI/Web/src/app/sidenav/_components/side-nav/side-nav.component.ts]: Spaces around -

**Review by majora2007 — COMMENTED** [review]
I will take care of all these issues.
