### PR TITLE
Inherit web links for Series and bug fixes

### LINKED ISSUE #4112: Max items section shows -10000
### What happened?

When using ComicInfo.xml, the maximum items section displays -10000. Majora directly responded that this was intentional, but since it's not currently used, it seems like it needs to be fixed, so I'm filing this report.

I'm not sure if this should be done in FR, so I'm filing this as a bug report.

Image

### What did you expect?

It should be 0.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.7 - Stable

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome, Other iOS Browser

### Relevant log output

```shell

```

### Additional Notes

majora2007 (Joe) —
Yes, it's an internal encoding. It could be improved with a different value since it used to be helpful for me debugging, but nowadays, I don't use it much.

### LINKED ISSUE #4118: Charater ID URL issue
### What happened?

Image

In the case of characters, if you enter an ID, the staff is fixed, so it does not connect to the normal URL.

### What did you expect?

https://anilist.co/character/157215/Mei-Mei
You need to change it to anilist.co/character so that it can be linked to the URL address, or you need to enter the entire URL.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.8 - Stable

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #4137: Metadata Match UI Error
### What happened?

Image

I found a match, but there is a bug where the loading image does not disappear.
I'm not sure if it's continuously searching or if the loading image just doesn't disappear after searching.

If this is intentional, please close the case.

To remove the loading image, press the "Do not mach" button once and then press it again.

I'm writing this post because I believe this is a bug.

### What did you expect?

Once matching metadata is found, the loading image should disappear. If the search is ongoing, a notification should be displayed to indicate that the match has ended.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.8 - Stable

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #4138: Bookmarks View Series Button not working.
### What happened?

Image

This appears to be a UI bug, but I'm not sure why it's there.

After checking the series, I clicked "...," and there's a "View Series" option. I believe this feature was added incorrectly.

When I click "View Series" individually for each series, it works fine.
It only appears when I select it and click it. This confirms that the feature was added incorrectly and needs to be removed.

### What did you expect?

I think that button should be removed.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.8 - Stable

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #4146: Bugs that change character names to aliases and do not save aliases when creating new names
### What happened?

I have a question to ask. When importing metadata through kavita+, the English name character whose character name is anilist is imported as it is. 
Since I use a different national language, if I try to put an English name character in my nickname and change the basic name to my national language, there is a problem that it is impossible to register in my nickname because the English name character is already in my name. 

In this case, you have to first erase the English name character, change it to my national language character name, save it, and then go through unnecessary work to add a nickname. 

For your information, there is no one with the same name. 

 I uploaded it to Discord because the video was not attached. 

### What did you expect?

When a name is a nickname and a new name is added, the name and nickname must be stored normally. 

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.8 - Stable

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

https://discord.com/channels/821879810934439936/1128053392065953812/1430986191490257130

### PR DESCRIPTION
**Pull request by Fesaa**
# Added
- Added: Added a library setting to automatically copy weblinks from the first chapter in a series to the series. Defaults to false. (Closes FR #3857, 2 upvotes)

# Changed
- Changed: Highest count in series info will now show no data if it's an internal magic number. (Closes #4112)
- Changed: People pages will now also show external links to MyAnimeList and Hardcover if their respective IDs are configured

# Fixed
- Fixed: Fixed not being able to change a person's name and use it as an alias in the same action. (Fixes #4146)
- Fixed: Fixed bulk bookmark actions, showing view series. (Fixes #4138)
- Fixed: Fixed logging out with OIDC throwing an exception when using Authelia
- Fixed: Fixed some OIDC errors showing a json response rather than redirecting to the login screen
- Fixed: Fixed a potential edge case in the match modal code, allowing the spinner to stay indefinitely (Closes #4137)
- Fixed: Fixed broken link image being the wrong colour for light/dark themes
- Fixed: Fixed chapter detail, always showing a link to Kavita
- Fixed: Fixed character external AniList links being incorrect (Closes #4118)

### CODE REVIEW

File: API/Controllers/PersonController.cs [hunk 1]
```diff
@@ -236,17 +277,17 @@ public async Task<ActionResult<PersonDto>> MergePeople(PersonMergeDto dto)
...
     {
-        var person = await _unitOfWork.PersonRepository.GetPersonById(personId, PersonIncludes.Aliases);
+        var person = await _unitOfWork.PersonRepository.GetPersonById(dto.PersonId, PersonIncludes.Aliases);
         if (person == null) return NotFound();
 
-        var existingAlias = await _unitOfWork.PersonRepository.AnyAliasExist(alias);
-        return Ok(!existingAlias && person.NormalizedName != alias.ToNormalized());
+        var aliasIsName = dto.Name.ToNormalized() == dto.Alias.ToNormalized();
+        var existingAlias = await _unitOfWork.PersonRepository.AnyAliasExist(dto.Alias);
+        return Ok(!existingAlias && !aliasIsName);
```
Comment (majora2007) [inline API/Controllers/PersonController.cs:292]: Try to get into the habit of adding a newline above return statements to make the code easier to navigate.

File: API/DTOs/Person/PersonAliasCheckDto.cs [hunk 2]
```diff
@@ -0,0 +1,17 @@
+namespace API.DTOs;
+
+public class PersonAliasCheckDto
+{
+    /// <summary>
+    /// The person to check against
+    /// </summary>
+    public int PersonId { get; set; }
```
Comment (majora2007) [inline API/DTOs/Person/PersonAliasCheckDto.cs:11]: Use [Required] to signal to the api generator that this is required. Users complained.

File: API/DTOs/Person/PersonAliasCheckDto.cs [hunk 3]
```diff
@@ -0,0 +1,17 @@
+namespace API.DTOs;
+
+public class PersonAliasCheckDto
```
Comment (majora2007) [inline API/DTOs/Person/PersonAliasCheckDto.cs]: Make this a sealed record.

File: API/DTOs/Person/PersonDto.cs [hunk 4]
```diff
@@ -38,4 +39,16 @@ public class PersonDto
...
     /// <remarks>Kavita+ Only</remarks>
     public string? HardcoverId { get; set; }
+
+    /// <summary>
+    /// Web links derived from the various id of external websites
+    /// </summary>
+    /// <remarks>Only present when retrieving from person info endpoint</remarks>
+    public IList<string>? WebLinks { get; set; } = [];
+    /// <summary>
+    ///
```
Comment (majora2007) [inline API/DTOs/Person/PersonDto.cs]: Is this all roles the person has?

File: API/Extensions/IdentityServiceExtensions.cs [hunk 5]
```diff
@@ -258,7 +261,47 @@ private static void SetupOpenIdConnectAuthentication(this IServiceCollection ser
...
-                OnTicketReceived = OidcClaimsPrincipalConverter,
+                OnTicketReceived = async ctx =>
+                {
+                    try
+                    {
+                        await OidcClaimsPrincipalConverter(ctx);
+                    }
+                    catch (KavitaException ex)
+                    {
+                        Log.Error(ex, "an exception occured during initial oidc flow");
```
Comment (majora2007) [inline API/Extensions/IdentityServiceExtensions.cs]: An should be captialized

Comment (majora2007) [reply API/Extensions/IdentityServiceExtensions.cs]: oidc should be OIDC

File: UI/Web/src/app/cards/_modals/edit-series-modal/edit-series-modal.component.html [hunk 6]
```diff
@@ -579,7 +579,11 @@ <h5>{{t('info-title')}}</h5>
                       <div class="mb-3">
                         <app-setting-item [title]="t('max-items-title')" [subtitle]="t('highest-count-tooltip')" [toggleOnViewClick]="false" [showEdit]="false">
                           <ng-template #view>
-                            {{metadata.maxCount}}
+                            @if (metadata.maxCount === LooseLeafOrDefaultNumber) {
+                              {{t('no-data')}}
```
Comment (majora2007) [inline UI/Web/src/app/cards/_modals/edit-series-modal/edit-series-modal.component.html:583]: Should we do no-data or should we do {{null | defaultValue}} (aka -)

**Review by majora2007 — CHANGES_REQUESTED** [review]

File: API/DTOs/Person/PersonDto.cs (hunk 4 above)
Comment (Fesaa) [reply API/DTOs/Person/PersonDto.cs]: Yes, same roles as returned by /api/person/roles. Added a summary

File: UI/Web/src/app/cards/_modals/edit-series-modal/edit-series-modal.component.html (hunk 6 above)
Comment (Fesaa) [reply UI/Web/src/app/cards/_modals/edit-series-modal/edit-series-modal.component.html:583]: I personally like no data more, as it then also implies your ComicInfo didn't have them set (/ the data is missing from your chapters). But I'm not sure, most of the web app does use -

Comment (majora2007) [reply UI/Web/src/app/cards/_modals/edit-series-modal/edit-series-modal.component.html:583]: Good point, no data works good for this.
