### PR TITLE
Progress Overhaul + Profile Page and a LOT more!

### LINKED ISSUE #3741: v8.5.0 PDF metadata support can't read some Full-Width/UTF Symbols (《, 》)
### What happened?

Cannot read Chinese font (e.g. 《乌托邦》) or maybe the "《" symbol in PDF metadata
The output is corrupted "ぎ䱢墐꘰"

### What did you expect?

Correct reading "乌托邦"

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.5.11 - Stable

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

Image
Image

### LINKED ISSUE #4099: Progress Enhancement
In order for Kavita to bring richer stats for users (Year in Review) and to more accurately track reading history (multiple re-reads), Kavita needs to enhance it's base reading model. This is the primary architecture for the new system. 

### Reading Session
```
CREATE TABLE ReadingSession (
    Id INTEGER PRIMARY KEY,
    AppUserId INTEGER NOT NULL,
    StartTime DATETIME NOT NULL,
    EndTime DATETIME NULL,
    IsActive BOOLEAN DEFAULT 1,
    
    -- JSON column for rich activity data
    -- Format: { 
    --   "activities": [
    --     { 
    --       "chapterId": 123, 
    --       "volumeId": 45,
    --       "seriesId": 6,
    --       "libraryId": 1,
    --       "startPage": 1, 
    --       "endPage": 50, 
    --       "startTime": "2024-01-01T10:00:00Z",
    --       "endTime": "2024-01-01T10:25:00Z",
    --       "pagesRead": 50
    --     }
    --   ]
    -- }
    ActivityData JSON NOT NULL DEFAULT '{"activities":[]}',
    
    CreatedUtc DATETIME NOT NULL,
    LastModifiedUtc DATETIME NOT NULL,
    
    INDEX idx_user_active (AppUserId, IsActive),
    INDEX idx_token (SessionToken)
);
```

### ReadingHistory
This will be aggregated daily stats
```
CREATE TABLE ReadingHistory (
Id INTEGER PRIMARY KEY,
    AppUserId INTEGER NOT NULL,
    DateUtc DATE NOT NULL,
    
    -- JSON for richer daily data
    -- Format: {
    --   "totalMinutesRead": 120,
    --   "totalPagesRead": 240,
    --   "totalWords": 240, // Need to think more on this
    --   "uniqueChapters": [123, 124, 125],
    --   "uniqueSeries": [6, 7],
    --   "hourlyDistribution": { "10": 25, "11": 45, "14": 30, "20": 20 },
    --   "peakHour": 11,
    --   "longestSession": 45,
    --   "chapters": {
    --     "123": { "minutesRead": 30, "pagesRead": 60, "seriesId": 6 },
    --     ...
    --   }
    -- }
    Data JSON NOT NULL,
    
    CreatedUtc DATETIME NOT NULL,
    
    UNIQUE INDEX idx_user_date (AppUserId, Date),
    INDEX idx_date (Date)
);
```

### Progress Table Change
- Add TotalReads column, defaults to 0. Once the chapter is fully read, we mark as 1. This can drive the UI to prompt for re-read or handle magically. 

### High Level Flow
A reading session contains multiple different chapters being read in a period. 

1. Use starts reading Series A Chapter 1
2. ReaderService checks if there is an active session or not. If not, creates a new session and register it with ReadingSessionService, return session id.
3. Reader continues reading, the progress table and session is updated. 
4. User finishes Chapter 1 and moves to Chapter 2, session data is updated. 
5. User stops reading and leaves PC. 
6. ReadingSessionService timeout expires, closes the session (IsActive = false)
7. A scheduled job will aggregate and create the daily summary row. 

### Other Information
- Timeout will be set to 30 minutes. Each reading event will refresh the timeout. 
- On startup, close all sessions in case of partial shutdown
- UI does not need to send the session id as the userId will be used for internal session cache. 
- In the case of a reading session hitting midnight, the session will be closed and reopened, to allow for clean daily summary.

### Implementation Details 
- **ReadingSessionService** - manage active reading sessions with automatic timeout
- **Per-session timers** - Each active session has a 30 min inactivity timer 
- **Midnight rollover timer** - Close all sessions just after midnight (local server time)
- **Lazy expiration check** - validates sessions on access as fallback

#### Timer Behaviour
- **Default Timeout**: 30 mins of inactivity
- **Timer Refresh**: Debounced to 5 seconds to prevent excessive timer churn during rapid page scrolling)
- **Expiration Tracking**: `Expiration` timestamp always updated, even when timer isn't refreshed
- **Midnight rollover** - All active sessions closed at midnight, new sessions created lazily on next activity

### UI
The UI will prompt the user on pressing read if an in-progress chapter hasn't been read in X time. These options will be:
* Continue reading
* Restart at page 1
These can be pre-configured on the user preferences. 

### Extra Stuff (This is a checklist for implementation)
- Don't report progress on first load of reader
  - [x] Manga reader
  - [x] Epub reader
  - [x] Pdf reader
- [x] Update UI to show total read count
- [x] New UI Options for re-read flow

The UI will also show a total read counter for chapters and/or series.

### LINKED ISSUE #4185: Reading Profile Settings Button Not Working Issue
### What happened?

Image

Image

These two buttons don't work.

### What did you expect?

When you click that button, a window should appear where you can set up your profile.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #4186: Problems that are not immediately reflected when setting up the library
### What happened?

Image
If you set the settings as shown in the image, click Next, and then Save, the language won't be saved.

You must immediately click Save after making the changes for them to take effect.

Library cover images also have the same issue.

### What did you expect?

After making changes, the information values ​​should be maintained and reflected when you click Save.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

To implement this, follow the steps above:

Add Library
Set Library Folder -> Load Cover Image -> Language Settings -> Tasks -> Save

### LINKED ISSUE #4198: On library creation, "Remove common prefixes for Sort Name" setting is not being saved
### What happened?

When you create a new library and click the slider for "Remove common prefixes for Sort Name" to On, it does not save (library creation proceeds but the setting is off). This is especially irritating as there's no way to stop the scan short of a shutdown, so the initially added series do not receive the benefit of this setting.

### What did you expect?

Setting is saved and applied as selected before initial scan

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.8 - Stable

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #4206: The problem of not being able to remove the relationship chart at once.
### What happened?

Death Note Standard Edition
Death Note Color Edition
There are two libraries.

I previously set the Standard Edition to Edition in the Color Edition and then set Specials in the Standard Edition. However, when I try to remove the relationship, it keeps returning to the home screen and I keep getting an error.

After several attempts, the removal process sometimes succeeded, but before that, the error persisted.

It's a bit difficult to explain exactly what's happening, so I'll attach a GIF image.

Image

ps.
If I specify a relationship with Edition, shouldn't the Parent relationship be specified?

### What did you expect?

I need to be able to remove the relationship without having to go back to the home screen.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #4213: Cannot re-authenticate after the first time, have to restart the container.
### What happened?

Everyday, after the authentication token expired, when accessing kavita, instead of seeing the authentication page, it returns a json error page instead

Image

### What did you expect?

Re-direct to authentik to re-authenticate.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell
Starting Kavita
ls -l /kavita/config/appsettings.json
[Kavita] [2025-11-14 16:31:02.743 -08:00  ] [Error]  Failed to load OIDC configuration, OIDC will not be enabled. Restart to retry
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://auth.xxx.com/application/o/kavita/.well-known/openid-configuration'. Will retry at '11/15/2025 00:31:02 +00:00'. Exception: 'System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.InjectNewHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.SendAndRetryOnNetworkErrorAsync(HttpClient httpClient, Uri uri)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)'.
 ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.InjectNewHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.SendAndRetryOnNetworkErrorAsync(HttpClient httpClient, Uri uri)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync()
   at API.Extensions.IdentityServiceExtensions.SetupOpenIdConnectAuthentication(IServiceCollection services, AuthenticationBuilder auth, OpenIdConnectSettings settings, IWebHostEnvironment environment) in /home/runner/work/Kavita/Kavita/API/Extensions/IdentityServiceExtensions.cs:line 170
[Kavita] [2025-11-14 16:31:04.297 -08:00  8] [Information] API.Program Running Manual Migrations
[Kavita] [2025-11-14 16:31:04.598 -08:00  8] [Information] API.Program Running Manual Migrations - complete
[Kavita] [2025-11-14 16:31:05.799 -08:00  1] [Information] API.Services.TaskScheduler Scheduling reoccurring tasks
[Kavita] [2025-11-14 16:31:05.900 -08:00  1] [Information] API.Services.TaskScheduler Scheduling Auto-Update tasks
[Kavita] [2025-11-14 16:31:05.960 -08:00  12] [Information] API.Program Running Migrations
[Kavita] [2025-11-14 16:31:06.138 -08:00  12] [Information] API.Program Running Migrations - complete
[Kavita] [2025-11-14 16:31:06.374 -08:00  1] [Information] API.Program Starting with base url as /
[Kavita] [2025-11-14 16:31:06.433 -08:00  1] [Information] API.Program Kavita - v0.8.8.6
[Kavita] [2025-11-14 16:31:06.676 -08:00  42] [Information] API.Services.Tasks.Scanner.LibraryWatcher [LibraryWatcher] Starting file watchers for 0 library folders
[Kavita] [2025-11-14 16:31:06.677 -08:00  42] [Information] API.Services.Tasks.Scanner.LibraryWatcher [LibraryWatcher] Watching 0 folders
[Kavita] [2025-11-14 16:31:07.169 -08:00  8] [Information] API.Controllers.PluginController Plugin Komf has authenticated with Administrator (1)'s API Key
[Kavita] [2025-11-14 16:31:07.310 -08:00  8] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST "/api/plugin/authenticate?apiKey=******REDACTED******&pluginName=Komf" responded 200 in 188.1033 ms
[Kavita] [2025-11-14 16:31:07.406 -08:00  42] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 2.9245 ms
[Kavita] [2025-11-14 16:31:17.042 -08:00  8] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 22.5263 ms
[Kavita] [2025-11-14 16:46:17.049 -08:00  70] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 1.6709 ms
[Kavita] [2025-11-14 17:01:17.060 -08:00  104] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 1.1628 ms
[Kavita] [2025-11-14 17:16:17.070 -08:00  84] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 1.3373 ms
[Kavita] [2025-11-14 17:31:17.078 -08:00  45] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 1.2655 ms
[Kavita] [2025-11-14 17:46:17.086 -08:00  47] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 1.3221 ms
[Kavita] [2025-11-14 18:01:17.094 -08:00  87] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 0.8576 ms
[Kavita] [2025-11-14 18:16:17.100 -08:00  94] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 0.9458 ms
[Kavita] [2025-11-14 18:31:12.289 -08:00  59] [Information] API.Controllers.PluginController Plugin Tachiyomi-Kavita has authenticated with tanpro260196 (11)'s API Key
[Kavita] [2025-11-14 18:31:12.317 -08:00  59] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST "/api/Plugin/authenticate?apiKey=******REDACTED******&pluginName=Tachiyomi-Kavita" responded 200 in 36.7466 ms
[Kavita] [2025-11-14 18:31:12.385 -08:00  59] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/Library/libraries responded 200 in 51.6811 ms
[Kavita] [2025-11-14 18:31:12.393 -08:00  54] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/Metadata/age-ratings responded 200 in 11.8693 ms
[Kavita] [2025-11-14 18:31:12.394 -08:00  58] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/Metadata/publication-status responded 200 in 12.6186 ms
[Kavita] [2025-11-14 18:31:12.402 -08:00  53] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/filter responded 200 in 20.4285 ms
[Kavita] [2025-11-14 18:31:12.424 -08:00  52] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/Collection responded 200 in 42.7694 ms
[Kavita] [2025-11-14 18:31:12.435 -08:00  56] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/Metadata/languages responded 200 in 56.0794 ms
[Kavita] [2025-11-14 18:31:12.444 -08:00  62] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/Metadata/genres responded 200 in 62.6403 ms
[Kavita] [2025-11-14 18:31:12.452 -08:00  51] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/Metadata/tags responded 200 in 69.3827 ms
[Kavita] [2025-11-14 18:31:12.500 -08:00  55] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/Metadata/people responded 200 in 118.5646 ms
[Kavita] [2025-11-14 18:31:17.114 -08:00  55] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 7.7416 ms
[Kavita] [2025-11-14 18:46:17.120 -08:00  135] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 1.0989 ms
[Kavita] [2025-11-14 19:01:17.128 -08:00  169] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 1.2337 ms
[Kavita] [2025-11-14 19:16:17.139 -08:00  181] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 1.3914 ms
[Kavita] [2025-11-14 19:31:17.149 -08:00  141] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 1.0779 ms
[Kavita] [2025-11-14 19:46:17.158 -08:00  120] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 1.1325 ms
[Kavita] [2025-11-14 20:01:17.164 -08:00  149] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 0.8190 ms
[Kavita] [2025-11-14 20:16:17.172 -08:00  104] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 1.3586 ms
[Kavita] [2025-11-14 20:31:17.180 -08:00  156] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 0.9399 ms
[Kavita] [2025-11-14 20:46:17.187 -08:00  121] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 1.2505 ms
[Kavita] [2025-11-14 21:01:17.195 -08:00  144] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 0.8433 ms
[Kavita] [2025-11-14 21:14:54.043 -08:00  174] [Error] API.Middleware.ExceptionMiddleware There was an exception
System.InvalidOperationException: No authentication handler is registered for the scheme 'OpenIdConnect'. The registered schemes are: DynamicHybrid, LocalIdentity. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("OpenIdConnect",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at API.Middleware.SecurityEventMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/SecurityMiddleware.cs:line 26
   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/ExceptionMiddleware.cs:line 24
[Kavita] [2025-11-14 21:14:54.088 -08:00  174] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /favicon.ico responded 404 in 0.0778 ms
[Kavita] [2025-11-14 21:15:13.410 -08:00  175] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 1.1267 ms
[Kavita] [2025-11-14 21:15:13.533 -08:00  178] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/account/oidc-authenticated responded 200 in 4.2512 ms
[Kavita] [2025-11-14 21:15:13.575 -08:00  184] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 25.4123 ms
[Kavita] [2025-11-14 21:15:13.607 -08:00  104] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/settings/oidc responded 200 in 5.9835 ms
[Kavita] [2025-11-14 21:15:13.629 -08:00  172] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/admin/exists responded 200 in 28.0782 ms
[Kavita] [2025-11-14 21:15:13.643 -08:00  172] [Error] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /oidc/login responded 500 in 2.3781 ms
System.InvalidOperationException: No authentication handler is registered for the scheme 'OpenIdConnect'. The registered schemes are: DynamicHybrid, LocalIdentity. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("OpenIdConnect",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at API.Startup.<>c.<<Configure>b__4_5>d.MoveNext() in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 447
--- End of stack trace from previous location ---
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
[Kavita] [2025-11-14 21:15:13.645 -08:00  172] [Error] API.Middleware.ExceptionMiddleware There was an exception
System.InvalidOperationException: No authentication handler is registered for the scheme 'OpenIdConnect'. The registered schemes are: DynamicHybrid, LocalIdentity. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("OpenIdConnect",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at API.Startup.<>c.<<Configure>b__4_5>d.MoveNext() in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 447
--- End of stack trace from previous location ---
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at API.Middleware.SecurityEventMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/SecurityMiddleware.cs:line 26
   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/ExceptionMiddleware.cs:line 24
[Kavita] [2025-11-14 21:15:13.646 -08:00  178] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/locale responded 200 in 98.6832 ms
[Kavita] [2025-11-14 21:15:13.664 -08:00  172] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /favicon.ico responded 404 in 0.0492 ms
[Kavita] [2025-11-14 21:15:23.870 -08:00  178] [Error] API.Middleware.ExceptionMiddleware There was an exception
System.InvalidOperationException: No authentication handler is registered for the scheme 'OpenIdConnect'. The registered schemes are: DynamicHybrid, LocalIdentity. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("OpenIdConnect",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at API.Middleware.SecurityEventMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/SecurityMiddleware.cs:line 26
   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/ExceptionMiddleware.cs:line 24
[Kavita] [2025-11-14 21:15:23.893 -08:00  178] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /favicon.ico responded 404 in 0.0901 ms
[Kavita] [2025-11-14 21:15:26.440 -08:00  178] [Error] API.Middleware.ExceptionMiddleware There was an exception
System.InvalidOperationException: No authentication handler is registered for the scheme 'OpenIdConnect'. The registered schemes are: DynamicHybrid, LocalIdentity. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("OpenIdConnect",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at API.Middleware.SecurityEventMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/SecurityMiddleware.cs:line 26
   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/ExceptionMiddleware.cs:line 24
[Kavita] [2025-11-14 21:16:17.203 -08:00  171] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 1.0944 ms
```

### Additional Notes

_No response_

### LINKED ISSUE #4217: Webtoon mode icon is the same as vertical reading mode icon in image reader
### What happened?

The icon that used to distinguish webtoon mode ↕️ is gone and now both vertical and webtoon mode have the same icon making it hard to distinguish which mode you are in while in the reader.

### What did you expect?

Icon is changed back or if unavailable to a new icon to better distinguish the 2 modes while in the reader

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #4228: "Lock" status of fields within a single comic aren't accurate
### What happened?

I've been seeing odd behavior when trying to edit and manually "lock" metadata fields within a single comic issue. In particular, if I try to lock the release date / title / sort order then click "save", then re-open the edit dialog, those fields will still appear unlocked.

I've tried refreshing the browser window, changing the value within the field while locking it, and restarting Kavita, but nothing changes this behavior.

Interestingly, I think it's still successfully locking these fields. If I change the release date within Kavita while attempting to lock it, then trigger a scan of that series, Kavita *does not* overwrite that field with the different date saved in the ComicInfo file.

A similar bug I noticed is with the "language" field, again for a single comic issue. Every time a open the edit dialog, it feels like 50-50 whether Kavita will correctly load both the lock status and value I have saved. Often, it will appear to be both unlocked and empty when I know that's not accurate. Again, re-opening the edit dialog enough times will eventually get it to load correctly.

The age rating and summary fields do not seem to be affected. I haven't tested any of the fields under the "tags" or "people" tabs.

All of this is using the newer "Comic" library type. I haven't tested anything with the older "Comic (Flexible)" library type.

### What did you expect?

Simply, the edit dialog should accurately and consistently display the current lock status and values of these metadata fields.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.8 - Stable

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

No

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

Kavita is running from a docker container on Unraid.

My web browser is a fork of Firefox called Waterfox, running on a Windows PC.

My CBZs have embedded ComicInfo files created by ComicRack. I am then running Komf to edit the metadata through the API (not the ComicInfo), primarily to replace the "cover date" with the "in store date" from Comic Vine. This works fine, but the release date field within Kavita needs to be locked afterward to prevent a routine scan from overwriting that newly scraped data with the embedded ComicInfo data. It would be great if I could lock those release date fields automatically, or even with a bulk edit of the series, but that's something I can look into later.

### LINKED ISSUE #4241: OpenID Connect using Authelia(& FreeIPA)
### What happened?

I followed the steps in Discord channel to setup Kavita with Authelia. I am encountering the following error. I use FreeIPA as my authentication backend. FreeIPA only let me to create all lower case groups. So, I was only able to create 'app-kavita-admin' and 'app-kavita-login'. Could this be causing the issue?  

Image

### What did you expect?

Sign in with OpenID connect provider successfully. 

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.8 - Stable

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell
kavita_1       | [Kavita] [2025-11-29 06:34:03.432 +00:00  67] [Error] API.Middleware.ExceptionMiddleware There was an exception
kavita_1       | Kavita.Common.KavitaException: errors.oidc.role-not-assigned
kavita_1       |    at API.Services.OidcService.CreateNewAccount(HttpRequest request, ClaimsPrincipal principal, OidcConfigDto settings, String oidcId) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\OidcService.cs:line 246
kavita_1       |    at API.Services.OidcService.LoginOrCreate(HttpRequest request, ClaimsPrincipal principal) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\OidcService.cs:line 144
kavita_1       |    at API.Extensions.IdentityServiceExtensions.OidcClaimsPrincipalConverter(TicketReceivedContext ctx) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Extensions\IdentityServiceExtensions.cs:line 311
kavita_1       |    at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
kavita_1       |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
kavita_1       |    at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
kavita_1       |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
kavita_1       |    at API.Middleware.SecurityEventMiddleware.InvokeAsync(HttpContext context) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Middleware\SecurityMiddleware.cs:line 26
kavita_1       |    at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Middleware\ExceptionMiddleware.cs:line 24
```

### Additional Notes

_No response_

### LINKED ISSUE #4251: Epub files ignore the lock when the series scan is repeated, even if the metadata is locked.
### What happened?

It seems that the problem is continuing due to the problem I wrote before.
#4165 
In the case of Epub, if you add multiple people, such as writers, translators, and photographers, and scan the series, all of those people are added as Author.

I deleted this issue arbitrarily and then locked the field, but there is a problem that it is restored to its original state when rescanning.

Also, if you try to uninstall again after this recovery occurs, the removal will not take place unless you do certain things.

The following process is required for reproduction.
Epub Series Scan -> Edit Metadata -> Delete part of writer -> Save -> Rescan series -> Edit metadata -> Delete part of writer -> Save (not reflected) / To reflect this part, you have to save it after unlocking it and then go back into metadata editing to correct it and save it.

### What did you expect?

Locked fields should not be modified.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

https://github.com/user-attachments/assets/1a9dbaf4-02ca-45c2-84f2-3754af0c9fd0
This is a reproduction video.
For your information, if you re-scan the field locked and then after the data has been restored to its original state, it will not be reflected even if you remove it while unlocking the field, so it will only be reflected if you save it after unlocking it and go back in and correct it.

### PR DESCRIPTION
**Pull request by majora2007**
This is a massive overhaul to Kavita's progress system and Authentication middleware stack with MANY new features. We need your help to provide feedback and guidence. 

Before jumping into the features, please note that this is the first part of the stats overhaul with the new progress system. Server-level stats page will come afterwards. Some CSS and Mobile views are not finished, @therobbiedavis is polishing and his work will come in a later PR. **Feedback is critical.**

### Auth Keys
I've heard complaints about my initial api key being too long and being a pain to type into eink devices, where copy isn't possible. Now, you can create your own Auth keys with their own expiration, and configure the key length from 8-32 characters. By default, Kavita will migrate your existing OPDS key for you. While you cannot delete this, you can refresh it and make it shorter. Kavita will also email users when their keys are about to expire or have fully expired if SMTP is setup on the server. 

### Devices Overhaul
image
image

To tie in with the new Auth Keys, I wanted a way to understand what devices are actually interacting with my server and are they active now (as an admin). Kavita now tracks how users connect with the server and tracks activities against said devices. In addition, when users are reading, Kavita will track it and allow admin's to see, in real time, details of the user's reading session. 

### User Profiles
image
image
image

User's now have their own profile that is like a shareable Stats page with a bit more. We've taken heavy inspiration from the excellent stats page from [Hardcover](https://hardcover.app). Profiles will always be visible to you and you can set your profile picture there, however, other users cannot see your profile if you do not share it (aka opt-in). 

### Re-reading/Multiple Reads
image
image

A new system was added to help with keeping track of total reads and help you jog your memory when coming back to a Series/book after a few weeks. By default, if no progress has occurred after 30 days, a prompt will launch on reading any books with progress prompting if you want to start over. Likewise, if you've already read in full, you will be prompted. This feature can be disabled entirely in settings.

# Added
- Added: User LastActive will now be updated on any activity with Kavita
- Added: Kavita now tracks all interactions with it for authenticated users/api/opds and will create a Client Device to represent interactions. Users can rename the devices or remove them. Devices contain some basic fingerprinting to avoid creating necessary noise. 
- Added: Kavita now allows admin's to see who is interacting with their server, on what device, and if they are active or not. 
- Added: Kavita now tracks reading sessions and will drive statistics from these. Reading sessions are created per-user on reading activity and expire after 30 minutes without further activity or at midnight. Reading sessions track what was read, how much, and total. Kavita will compact the data daily into a separate table for historical reasons with higher level aggregations. (Closes #4099)
- Added: Kavita will now keep track of how many times you read a chapter/series
- Added: Kavita will now prompt you if you haven't read a chapter after X days (configurable in settings) to either start over from the beginning, read incognito, or continue as-is. Reading over from the beginning will trigger a total read count increment. 
- Added: Added the ability to have a personalized profile screen to share with other users on the server. This is an opt-in feature. Profile screen will show information about what you do on the server, interesting facts about your reading habits, and reviews (a separate opt-in control). 
- Added: Users can now upload a profile image of themselves for their profile page and any other social interactions. 
- Added: Added the ability to create named Auth Keys with custom length (8-32 characters), expiration date per-user. Kavita will email users that the key is expiring soon or has expired if email is setup on the instance. (Closes FR #3539, 3 upvotes)
- Added: Added the ability to filter annotations by likes

# Changed
- Changed: Opening the readers will no longer send a progress even immediately, you must paginate/scroll to send progress.
- Changed: Email-based devices are now called Email Devices to not clash with new Client Devices. 
- Changed: Review cards username can be clicked to load their profile. 
- Changed: Updated to .NET 10
- Changed: Remove default keybinds referencing meta keys (Windows Key)
- Changed: Updated the design of the tooltips across the app for better contrast
- Changed: Do not use OIDC Authentication scheme if OIDC failed to initialize. Extra fail safes in case users OIDC did not initialize successfully, to not auto redirect etc
- Changed: Removed API Key from User 
- Changed: Streamlined LastActive for user accounts to be handled for any API activity
- Changed: (Kavita+) Don't block startup to check for K+ license, do it in a background thread instead.
- Changed: OIDC roles are now case insensitive when syncing. (Closes #4241)

# Fixed
- Fixed: Fixed some flakiness with the keybind pickers
- Fixed: Readonly role handling wasn't explicitly on the annotation code
- Fixed: Fixed a bug where lastReadDate wasn't being calculated correctly on multiple APIs (#4180)
- Fixed: Some old migrations were running on each startup for no reason
- Fixed: Some old app users (~4 years ago) didn't have createdUtc filled correctly for their User Table
- Fixed: Some old migrations were missing date columns in AppUserRating
- Fixed: Only show entity size on detail pages when the user is admin or has download role.
- Fixed: Fix ChapterDto missing some locks. (Fixes #4228, Fixes #4251)
- Fixed: Fixed webtoon reading mode icon being incorrect (Closes #4217)
- Fixed: Fixed edit series relationship form not always rendering names
- Fixed: Fixed not being able to remove the first series relationship (Closes #4206)
- Fixed: Potential fix for bookmark image button in epub reader positioned poorly (#4205)
- Fixed: Fixed default language, Remove Sort Prefix, and Inherit web links from first chapter not saving on library creation (Fixes #4198, Fixes #4186)
- Fixed: Fixed Reading Profile action menu not working on library detail page (Fixes #3741, Fixes #4185 )
- Fixed: Fixed OIDC not being enabled if the IDP is not reachable at startup. Must be reachable on the first request. (Closes #4213)

# Theme
- Added css variables to style tooltips: --tooltip-caret-color, --tooltip-bg-color, --tooltip-outline-color
- Added misc css variable --offwhite-text-color

# API
- GET /api/upload/reset-chapter-lock has been marked deprecated and will be removed in v0.9.0
- POST /api/want-to-read/ will be removed in v0.9.0, use v2 instead
- POST /api/account/reset-api-key is removed, use /api/account/rotate-auth-key

### CODE REVIEW

File: API/Controllers/AccountController.cs [hunk 1]
```diff
@@ -118,32 +128,31 @@
...
+    [DisallowRole(PolicyConstants.ReadOnlyRole)]
     public async Task<ActionResult> UpdatePassword(ResetPasswordDto resetPasswordDto)
     {
         var user = await _userManager.Users.SingleOrDefaultAsync(x => x.UserName == resetPasswordDto.UserName);
         if (user == null) return Ok(); // Don't report BadRequest as that would allow brute forcing to find accounts on system
 
-        _logger.LogInformation("{UserName} is changing {ResetUser}'s password", User.GetUsername(), resetPasswordDto.UserName);
-        if (User.IsInRole(PolicyConstants.ReadOnlyRole))
-            return BadRequest(await _localizationService.Translate(User.GetUserId(), "permission-denied"));
+        _logger.LogInformation("{UserName} is changing {ResetUser}'s password", Username!, resetPasswordDto.UserName);
```
[the remark this answers is not in the document]
Comment (majora2007) [reply API/Controllers/AccountController.cs]: We need to use .Sanatize() on the dto value for logging

[the remark this answers is not in the document]
Comment (majora2007) [reply API/Controllers/AccountController.cs]: We need to use .Sanatize() on the dto value for logging

File: API/Controllers/ActivityController.cs [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+using API.Constants;
+using API.Data;
+using API.DTOs.Progress;
+using API.Services;
+using Microsoft.AspNetCore.Authorization;
+using Microsoft.AspNetCore.Mvc;
+
+namespace API.Controllers;
+
+// TODO: Move all this to a SessionController or something
```
Comment (majora2007) [inline API/Controllers/ActivityController.cs]: Remove TODO

File: API/Controllers/ImageController.cs [hunk 3]
```diff
@@ -326,19 +337,26 @@ public async Task<ActionResult> GetPersonCoverImageByName(string name, string ap
...
+    /// <param name="apiKey"></param>
     /// <returns></returns>
-    [Authorize(Policy="RequireAdminRole")]
     [HttpGet("cover-upload")]
     [ResponseCache(CacheProfileName = ResponseCacheProfiles.Images, VaryByQueryKeys = ["filename", "apiKey"])]
     public async Task<ActionResult> GetCoverUploadImage(string filename, string apiKey)
     {
-        if (await _unitOfWork.UserRepository.GetUserIdByApiKeyAsync(apiKey) == 0) return BadRequest();
-        if (filename.Contains("..")) return BadRequest(await _localizationService.Translate(User.GetUserId(), "invalid-filename"));
+        if (await _unitOfWork.UserRepository.GetUserIdByAuthKeyAsync(apiKey) == 0) return BadRequest();
```
Comment (majora2007) [inline API/Controllers/ImageController.cs]: This shouldn't be needed since we have UserContext here.

File: API/Controllers/LibraryController.cs [hunk 4]
```diff
@@ -642,6 +667,8 @@ await _eventHub.SendMessageAsync(MessageFactory.SideNavUpdate,
 
     private void UpdateLibrarySettings(UpdateLibraryDto dto, Library library, bool updateType = true)
     {
+        // ALSO ADD NEW FIELDS IN THE CREATE LIBRARY ENDPOINT
```
Comment (majora2007) [inline API/Controllers/LibraryController.cs]: @Fesaa do you know what we need here?

File: API/Controllers/ReaderController.cs [hunk 5]
```diff
@@ -792,16 +794,23 @@ public async Task<ActionResult> BookmarkPage(BookmarkDto bookmarkDto)
     [HttpPost("unbookmark")]
```
Comment (majora2007) [inline API/Controllers/ReaderController.cs:802]: If we have an AllowRole middleware or authorize policy for Bookmark role, let's use it.

File: API/Controllers/ReaderController.cs [hunk 6]
```diff
@@ -862,12 +872,13 @@ public async Task<ActionResult<HourEstimateRangeDto>> GetEstimateToCompletion(in
             // Word count
             var progressCount = chapters.Sum(c => c.WordCount);
             var wordsLeft = series.WordCount - progressCount;
-            return _readerService.GetTimeEstimate(wordsLeft, 0, true);
+            return ReaderService.GetTimeEstimate(wordsLeft, 0, true);
```
Comment (majora2007) [inline API/Controllers/ReaderController.cs:883]: Missing Ok()

File: API/Controllers/ReaderController.cs [hunk 7]
```diff
@@ -882,19 +893,19 @@ public async Task<ActionResult<HourEstimateRangeDto>> GetEstimateToCompletion(in
...
         // Patch in the reading progress
-        await _unitOfWork.ChapterRepository.AddChapterModifiers(User.GetUserId(), chapter);
+        await _unitOfWork.ChapterRepository.AddChapterModifiers(UserId, chapter);
 
         if (series.Format == MangaFormat.Epub)
         {
             // Get the word counts for all the pages
             var pageCounts = await _bookService.GetWordCountsPerPage(chapter.Files.First().FilePath); // TODO: Cache
-            if (pageCounts == null) return _readerService.GetTimeEstimate(series.WordCount, 0, true);
+            if (pageCounts == null) return ReaderService.GetTimeEstimate(series.WordCount, 0, true);
```
Comment (majora2007) [inline API/Controllers/ReaderController.cs:916]: Missing Ok() in this method

File: API/Controllers/SettingsController.cs [hunk 8]
```diff
@@ -216,11 +213,11 @@ public ActionResult<bool> IsValidCron(string cronExpression)
...
     /// </summary>
     /// <returns></returns>
-    [Authorize(Policy = "RequireAdminRole")]
+    [Authorize(Policy = PolicyGroups.AdminPolicy)]
     [HttpPost("test-email-url")]
     public async Task<ActionResult<EmailTestResultDto>> TestEmailServiceUrl()
     {
-        var user = await _unitOfWork.UserRepository.GetUserByIdAsync(User.GetUserId());
+        var user = await _unitOfWork.UserRepository.GetUserByIdAsync(UserId);
         if (string.IsNullOrEmpty(user?.Email)) return BadRequest("Your account has no email on record. Cannot email.");
```
Comment (majora2007) [inline API/Controllers/SettingsController.cs:221]: We are missing a localization here

File: API/Controllers/StatsController.cs [hunk 9]
```diff
@@ -24,122 +27,109 @@ namespace API.Controllers;
...
-        _userManager = userManager;
-        _localizationService = localizationService;
-        _licenseService = licenseService;
-        _directoryService = directoryService;
-    }
-
     [HttpGet("user/{userId}/read")]
-    [ResponseCache(CacheProfileName = "Statistics")]
+    [ResponseCache(CacheProfileName = ResponseCacheProfiles.Statistics)]
     public async Task<ActionResult<UserReadStatistics>> GetUserReadStatistics(int userId)
```
Comment (majora2007) [inline API/Controllers/StatsController.cs:40]: Should use [Authorize(PolicyGroups.AdminPolicy)] instead of custom user lookup

File: API/Controllers/StatsController.cs [hunk 10]
```diff
@@ -157,41 +147,41 @@ public async Task<ActionResult> DownloadFilesByExtension(string fileExtension)
...
         var isAdmin = User.IsInRole(PolicyConstants.AdminRole);
         if (!isAdmin && userId != user!.Id) return BadRequest();
 
-        return Ok(await _statService.ReadCountByDay(userId, days));
+        return Ok(await statService.ReadCountByDay(userId, days));
     }
 
     [HttpGet("day-breakdown")]
-    [ResponseCache(CacheProfileName = "Statistics")]
+    [ResponseCache(CacheProfileName = ResponseCacheProfiles.Statistics)]
```
Comment (majora2007) [inline API/Controllers/StatsController.cs:161]: [Authorize(PolicyGroups.AdminPolicy)]

File: API/Controllers/StatsController.cs [hunk 11]
```diff
@@ -157,41 +147,41 @@ public async Task<ActionResult> DownloadFilesByExtension(string fileExtension)
...
 
     [HttpGet("user/reading-history")]
-    [ResponseCache(CacheProfileName = "Statistics")]
+    [ResponseCache(CacheProfileName = ResponseCacheProfiles.Statistics)]
     public async Task<ActionResult<IEnumerable<ReadHistoryEvent>>> GetReadingHistory(int userId)
     {
-        var user = await _unitOfWork.UserRepository.GetUserByUsernameAsync(User.GetUsername());
+        var user = await unitOfWork.UserRepository.GetUserByUsernameAsync(Username!);
         var isAdmin = User.IsInRole(PolicyConstants.AdminRole);
         if (!isAdmin && userId != user!.Id) return BadRequest();
```
Comment (majora2007) [inline API/Controllers/StatsController.cs:182]: Reads as a [Authorize(PolicyGroups.AdminPolicy)], but we might want to just redo these apis with the new stats page.

File: API/Data/ManualMigrations/v0.8.9/MigrateProgressToReadingSessions.cs [hunk 12]
```diff
@@ -0,0 +1,178 @@
...
+namespace API.Data.ManualMigrations;
+
+
+/// <summary>
+/// v0.8.9 - Convert past progress into Reading Sessions
+/// </summary>
+public class MigrateProgressToReadingSessions : ManualMigration
+{
+    private const int BatchSize = 1000;
+    public const string Name = nameof(MigrateProgressToReadingSessions);
```
Comment (majora2007) [inline API/Data/ManualMigrations/v0.8.9/MigrateProgressToReadingSessions.cs:24]: Remove Name, not needed

File: API/Helpers/BrowserHelper.cs [hunk 13]
```diff
@@ -0,0 +1,86 @@
+﻿using System;
+using API.Entities.Enums;
+
+namespace API.Helpers;
```
Comment (majora2007) [inline API/Helpers/BrowserHelper.cs:4]: Need to add nullable

File: API/Helpers/OpenIdConnectEventsHelper.cs [hunk 14]
```diff
@@ -0,0 +1,156 @@
...
+using API.Extensions;
+using API.Services;
+using Kavita.Common;
+using Microsoft.AspNetCore.Authentication;
+using Microsoft.AspNetCore.Authentication.OpenIdConnect;
+using Microsoft.AspNetCore.Http;
+using Microsoft.Extensions.DependencyInjection;
+using Serilog;
+
+namespace API.Helpers;
```
Comment (majora2007) [inline API/Helpers/OpenIdConnectEventsHelper.cs:14]: nullable enable

File: API/Middleware/ClientInfoMiddleware.cs [hunk 15]
```diff
@@ -0,0 +1,137 @@
...
+                    Orientation = match.Groups["orientation"].Success
+                        ? match.Groups["orientation"].Value
+                        : null,
+                    UserAgent = fallbackUa
+                };
+            }
+        }
+        catch (Exception ex)
+        {
+            logger.LogWarning(ex, "Failed to parse X-Kavita-Client header: {Header}", header);
```
[the remark this answers is not in the document]
Comment (majora2007) [reply API/Middleware/ClientInfoMiddleware.cs]: This needs to be done with .Sanitize()

File: API/Services/HostedServices/ReadingSessionInitializer.cs [hunk 16]
```diff
@@ -0,0 +1,46 @@
...
+        _logger.LogInformation("Ensuring all reading sessions are closed");
+
+        using var scope = _serviceScopeFactory.CreateScope();
+        var context = scope.ServiceProvider.GetRequiredService<DataContext>();
+
+        await context.AppUserReadingSession
+            .Where(s => s.EndTime == null)
+            .ExecuteUpdateAsync(s => s
+                .SetProperty(x => x.IsActive, false)
+                .SetProperty(x => x.EndTime, DateTime.Now)
```
Comment (majora2007) [inline API/Services/HostedServices/ReadingSessionInitializer.cs:36]: Need to align this with the ReadingSessionService, should be EndDate at now - default timeout

File: API/Services/StatisticService.cs [hunk 17]
```diff
@@ -1,21 +1,24 @@
-﻿using System;
+﻿#nullable enable
```
Comment (majora2007) [inline API/Services/StatisticService.cs]: This should be after namespace

File: API/Extensions/QueryExtensions/AuthKeyQueryExtensions.cs [hunk 18]
```diff
@@ -0,0 +1,13 @@
...
+using System.Linq;
+using API.Entities.User;
+
+namespace API.Extensions.QueryExtensions;
+
+public static class AuthKeyQueryExtensions
+{
+    public static IQueryable<AppUserAuthKey> IsNotExpired(this IQueryable<AppUserAuthKey> queryable)
+    {
+        return queryable.Where(k => k.ExpiresAtUtc == null || k.ExpiresAtUtc < DateTime.UtcNow);
```
[the remark this answers is not in the document]
Comment (majora2007) [reply API/Extensions/QueryExtensions/AuthKeyQueryExtensions.cs]: Good catch, and let's rename this to HasNotExprired

**Review by majora2007 — COMMENTED** [review]
Only did the backend due to the size and lag.

File: API/Controllers/LibraryController.cs (hunk 4 above)
Comment (Fesaa) [reply API/Controllers/LibraryController.cs]: It's just as a reminder for when we add new fields to the Library Entity. As every time we've added something in the past, we forgot to add it to the create library endpoint and get an issue "X is not saved when creating a new library"

File: API/Data/ManualMigrations/v0.8.9/MigrateProgressToReadingSessions.cs (hunk 12 above)
Comment (Fesaa) [reply API/Data/ManualMigrations/v0.8.9/MigrateProgressToReadingSessions.cs:24]: It's used in stats service to lookup when the migration has happened to cutoff the time by hour stats

File: API/Services/HostedServices/ReadingSessionInitializer.cs (hunk 16 above)
Comment (majora2007) [reply API/Services/HostedServices/ReadingSessionInitializer.cs:36]: Actually this runs on startup, so it's not needed.
