### PR TITLE
A handful of bugs

### LINKED ISSUE #4293: Editing Own Account as Admin - OIDC Related
### What happened?

The inability to edit one's own account within the admin portal causes some roadblocks (that thankfully have workarounds, thanks Amelia!).

- Unable to unlink OIDC from one's own account, potentially bricking/softlocking login
- Unable to edit your own username, which can also cause some friction with OIDC

For anyone searching through the internet looking for a fix to "email already in use by another account" - 
- you'll need to remove OIDC from Kavita
- click save
- re-add the OIDC

And for those of you having issues editing your OIDC through the GUI (I use a .in domain, and Kavita thinks it's sus, preventing me from editing any of the authority information):
- Navigate to your Kavita config folders
- Edit "appsettings.json" (mine's in my root Kavita folder, not the config folder)

Disclaimer: I'm a Docker via Portainer user, running authentik

### What did you expect?

Go to the users page, find the edit button for my own profile, edit necessary details.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.8 - Stable

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #4423: Wrong error code in changing language
### What happened?

On the instance of kavita (https://demo-next.kavitareader.com/) logged into a readonly account (translator) and tried changing the language, i got error 400. There is no message indicating that I lack permissions. 

### What did you expect?

Instead of getting error 400 i expected to get error 403

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #4438: Smart Filters Don't Show Up For Libraries Not In Dashbaord
### What happened?

Apologies if this is expected behavior but it took me a long time to figure this out. When you create a Smart Filter, if it happens to only-include files from a library that is configured to not be included in the dashboard, the filter simply doesn't show up. It's not listed under Smart Filters and therefor can not be edited or deleted, it's simply hidden. To reproduce this:

1. Create or edit a library
2. In the "Advanced Settings" tab, disable "Include in Dashboard"
3. Make sure it has a book or two
4. Go to "Smart Filters" and create a new filter
5. Set it to require all conditions, then define a condition that the books be in the library that was previously configured, optionally add additional filters
6. Save it and return to the "Smart Filters" screen, see that the number of smart filters does not equal the number that is visible
7. Go back to the library, enable "Include in Dashboard" and return to see that now the smart filter is visible, can be edited, deleted, etc.

### What did you expect?

I was expecting to see the smart filter I'd just created shown in the list. Not being able to edit or delete it was very confusing until I realized that the Library had to be set to be included in the dashboard.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.9.1 - Stable

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #4446: EPUB Reader: Progress syncing is off when switching between one- and two-column mode
### What happened?

When switching from a device with one-column mode to a device with two-column mode the virtual page might not be computed correctly according to the reading progress and jumps back to the top of the native page (as per EPUB metadata).
I have attached a video, where I have bookmarked the top of the page and when switching to another instance with a different column mode it jumps back to the bookmark. Happens to me regularly when I read on my smartphone and then switch to my tablet or desktop device with two-column mode.

https://github.com/user-attachments/assets/145d7a4e-5cde-41df-bc0f-c7d50193708b

### What did you expect?

The EPUB reader will start roughly at the position where last closed, unaffected by the reading mode. (During scroll mode and from one-column to one-column I didn't face any issues)

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.9.1 - Stable

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

Yes

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Safari

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #4454: Annotations Drawer Lag/Hanging Up
### What happened?

As the number of annotations increases for a series, the Annotation Drawer takes more and more time to open up both on PC and in PWA (with PWA being considerably slower).

At around 800 Annotations in a series, Annotations Drawer takes ~8 Seconds to open on PC and around ~30 Seconds+ on PWA.

### What did you expect?

Annotations Drawer to open up instantly/Not keep getting slower.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.9.1 - Stable

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

No

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #4499: Executing 'General Cleanup' did not remove 'empty tags'
### What happened?

After executing 'General Cleanup', the empty tags was not deleted

### What did you expect?

Is it possible to individually delete a specific tag or modify the information of a created tag?

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.9.1 - Stable

### Are you accessing kavita through a reverse proxy? If yes, confirm that the issue persists with a direct connection

No

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.515 +00:00  57] [Information] API.Controllers.ServerController LynxSpace is clearing running general cleanup from admin dashboard
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.516 +00:00  57] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/server/cleanup responded 200 in 6.1906 ms
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.527 +00:00  57] [Information] API.Services.Tasks.CleanupService Starting Cleanup
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.528 +00:00  57] [Information] API.Services.Tasks.CleanupService Cleaning temp directory
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.531 +00:00  53] [Information] API.Services.Tasks.CleanupService Cleaning cache and temp directories
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.532 +00:00  53] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache & Temp directories
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.538 +00:00  53] [Information] API.Services.Tasks.CleanupService Cache and temp directory purged
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.538 +00:00  53] [Information] API.Services.Tasks.CleanupService Cleaning old database backups
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.541 +00:00  53] [Information] API.Services.Tasks.CleanupService Beginning cleanup of Database backups at "2026-03-07T16:06:10.5413495+00:00"
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.546 +00:00  53] [Information] API.Services.Tasks.CleanupService All expired backups are older than 30 days. Removing all but last backup
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.546 +00:00  53] [Information] API.Services.Tasks.CleanupService Finished cleanup of Database backups at "2026-03-07T16:06:10.5468064+00:00"
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.547 +00:00  53] [Information] API.Services.Tasks.CleanupService Consolidating Progress Events
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.548 +00:00  53] [Information] API.Services.Tasks.CleanupService Consolidating Progress Events
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.552 +00:00  53] [Information] API.Services.Tasks.CleanupService Consolidating Media Errors
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.553 +00:00  53] [Information] API.Services.Tasks.CleanupService Beginning consolidation of 0 Media Errors
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.555 +00:00  53] [Information] API.Services.Tasks.CleanupService Finished consolidation of 0 Media Errors, Removed: 0
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.556 +00:00  53] [Information] API.Services.Tasks.CleanupService Cleaning abandoned database rows
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.571 +00:00  53] [Information] API.Services.Tasks.CleanupService Cleaning deleted series cover images
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.586 +00:00  53] [Information] API.Services.Tasks.CleanupService Cleaning deleted chapter cover images
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.597 +00:00  53] [Information] API.Services.Tasks.CleanupService Cleaning deleted cover images
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.613 +00:00  53] [Information] API.Services.Tasks.CleanupService Cleaning old logs
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.614 +00:00  53] [Information] API.Services.Tasks.CleanupService Performing cleanup of logs directory
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.620 +00:00  53] [Information] API.Services.Tasks.CleanupService Finished cleanup of logs at "2026-03-07T16:06:10.6208649+00:00"
2026-03-08 00:06:10


[Kavita] [2026-03-07 16:06:10.621 +00:00  53] [Information] API.Services.Tasks.CleanupService Cleaning progress events that exceed 100%
```

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by Fesaa**
# Added
- Added: Added a button to unlink your account from OIDC (Closes #4293)

# Changed
- Changed: Errored out smart filters can now be deleted from the smart filter page
- Changed: User preferences and keybinds will now be disabled for users with the Read Only role to avoid confusion (Closes #4423) (Thanks @IbrahimHamshari!)

# Fixed
- Fixed: Fixed orphaned tags not being cleaned up (Closes #4499)
- Fixed: Fixed profile overview not loading (develop)
- Fixed: Fixed paging back in the image reading opening chapters at the start
- Fixed: Fixed the annotation drawer in the book reader hanging when a large amount of annotations are present (Closes #4454)
- Fixed: Fixed smart filters with no results being completely hidden on the smart filter page (Closes #4438)
- Fixed: Fixed the delete smart filter action deleting collections instead (develop)
- Fixed: Fixed reading sessions in which an epub chapter was finished not having a recorded word count 
- Fixed: Fixed epub reader not saving the correct reading position under specific circumstances (Fixes #4446, #3022) (Thanks @vipin2310!)

### CODE REVIEW

File: UI/Web/src/app/manga-reader/_components/manga-reader/manga-reader.component.ts [hunk 1]
```diff
@@ -1087,8 +1087,16 @@ export class MangaReaderComponent implements OnInit, AfterViewInit, OnDestroy {
       this.continuousChapterInfos[ChapterInfoPosition.Current] = results.chapterInfo;
       this.volumeId = results.chapterInfo.volumeId;
       this.maxPages = results.chapterInfo.pages;
+
+
       let page = results.progress.pageNum;
-      if (page >= this.maxPages) {
+
+      // Progress for the last page is saved as maxPages, correct this here to be used as page number
+      if (page === this.maxPages) {
```
Comment (majora2007) [inline UI/Web/src/app/manga-reader/_components/manga-reader/manga-reader.component.ts:1096]: What is the bug around this code? The comment doesn't give any context.

**Review by majora2007 — CHANGES_REQUESTED** [review]

File: UI/Web/src/app/manga-reader/_components/manga-reader/manga-reader.component.ts (hunk 1 above)
Comment (Fesaa) [reply UI/Web/src/app/manga-reader/_components/manga-reader/manga-reader.component.ts:1096]: If you page back while reading in the image reader, you'll be sent to the first page of the previous chapter rather than the last (if you had completed that chapter).

Comment (majora2007) [reply UI/Web/src/app/manga-reader/_components/manga-reader/manga-reader.component.ts:1096]: Okay, it would be nice to have a better contextual message in the comment.

File: UI/Web/src/app/book-reader/_components/_drawers/view-annotations-drawer/view-annotations-drawer.component.scss [hunk 2]
```diff
@@ -15,3 +15,7 @@
   color: var(--drawer-text-color)
 }
 
+.virtual-scroller, virtual-scroller {
+  width: 100%;
+  height: 100vh;
```
[the remark this answers is not in the document]
Comment (Fesaa) [reply UI/Web/src/app/book-reader/_components/_drawers/view-annotations-drawer/view-annotations-drawer.component.scss:20]: Mmh, I didn't notice any issues while testing probably because it's a drawer. 100% doesn't work however, as nothing shows up then. I think it's fine, but not absolutely sure
