### PR TITLE
Fix reading lists not respecting age ratings

### LINKED ISSUE #3307: The age rating restriction option "Include Unknowns" doesn't work for Reading Lists.
### What happened?

Admin promoted Reading Lists are not available for users with age rating restriction with Include Unknowns activated.
Comics tested had Age Rating Unknown.

### What did you expect?

Reading Lists with Unknown Age Rating comics to be visible to users with age rating restriction but with Include Unknowns activated.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by Fesaa**
# Fixed
- Fixed: Fixed reading list not respecting age restrictions (Fixes #3307)

### CODE REVIEW

File: API/Data/Repositories/ReadingListRepository.cs [hunk 1]
```diff
@@ -185,10 +186,11 @@ public void BulkRemove(IEnumerable<ReadingListItem> items)
 
     public async Task<PagedList<ReadingListDto>> GetReadingListDtosForUserAsync(int userId, bool includePromoted, UserParams userParams, bool sortByLastModified = true)
     {
-        var userAgeRating = (await _context.AppUser.SingleAsync(u => u.Id == userId)).AgeRestriction;
+        var user = await _context.AppUser.SingleAsync(u => u.Id == userId);
```
Comment (majora2007) [inline API/Data/Repositories/ReadingListRepository.cs]: Use first instead. Single does an additional check that there is only one, which is overhead we don't need.

**Review by majora2007 — APPROVED** [review]
