### PR TITLE
Metadata Settings for all + Ability to Import/Export settings

### LINKED ISSUE #3847: quote breaks genre/tag mapping
### What happened?

Image
I have all of these field mappings set up and kavita partially ignores the '. in particular the tag i've been having an issue with is boys' love. i got the age rating to work by adding Boys Love to the age rating mappings but that doesnt help my use case as the age rating mapping i want to use is the Lgbtq+ themes tag which fails to get set despite the same Boys Love tag being there in the field mapping list.

### What did you expect?

the mapping needs to either ignore the ' entirely or recognize it so it can be used properly. either way would work fine.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by Fesaa**
# Added
- Added: Ability to export and import Metadata Settings
- Added: Brought the manage metadata settings from Kavita+ exclusively to all of Kavita and thus the ability to have it work against file/api-based metadata. (FR #3862, 1 vote)

# Changed
- Changed: Blacklist and whitelist, age rating, and field mappings are now available without Kavita+ 
- Changed: Blacklist and whitelist, age rating, and field mappings will now act on metadata data in your ComicInfo (Will require a scan) and via the API

# Fixed
- Fixed: Fixed field mappings not being normalized when matching (Fixes #3847)

### CODE REVIEW

File: API/Services/Tasks/ScannerService.cs [hunk 1]
```diff
@@ -641,19 +645,33 @@ private async Task<int> ProcessParsedSeries(bool forceUpdate, Dictionary<ParsedS
                                          .Split(",", StringSplitOptions.RemoveEmptyEntries) // Split on comma and remove empty entries
                                          .Select(g => g.Trim()) // Trim each genre
                                          .Where(g => !string.IsNullOrWhiteSpace(g)) // Ensure no null/empty genres
-                                     ?? [])); // Handle null Genre or ComicInfo safely
-
-            await CreateAllGenresAsync(allGenres.Distinct().ToList());
+                                     ?? []))  // Handle null Genre or ComicInfo safely
```
Comment (majora2007) [inline API/Services/Tasks/ScannerService.cs]: These comments aren't needed

File: UI/Web/src/app/admin/import-mappings/import-mappings.component.html [hunk 2]
```diff
@@ -0,0 +1,294 @@
...
+              </div>
+
+              <div class="col-md-6 col-sm-12 pt-4">
+                @if (importSettingsForm.get('blacklist'); as control) {
+                  <app-setting-switch [title]="t('blacklist-label')">
+                    <ng-template #switch>
+                      <div class="form-check form-switch">
+                        <input id="blacklist-enabled" type="checkbox" class="form-check-input" formControlName="blacklist">
+                      </div>
+                    </ng-template>
```
[the remark this answers is not in the document]
Comment (Fesaa) [reply UI/Web/src/app/admin/import-mappings/import-mappings.component.html:73]: I don't see any stray 's'

File: API/Services/Tasks/Scanner/ProcessSeries.cs [hunk 3]
```diff
@@ -311,14 +312,16 @@ private async Task UpdateSeriesMetadata(Series series, Library library)
...
-            var metadataSettings = await _unitOfWork.SettingsRepository.GetMetadataSettingDto();
-            var allTags = series.Metadata.Tags.Select(t => t.Title).Concat(series.Metadata.Genres.Select(g => g.Title));
-            var updatedRating = ExternalMetadataService.DetermineAgeRating(allTags, metadataSettings.AgeRatingMappings);
-            if (updatedRating > series.Metadata.AgeRating)
+            if (settings.EnableExtendedMetadataProcessing)
             {
-                series.Metadata.AgeRating = updatedRating;
+                var allTags = series.Metadata.Tags.Select(t => t.Title).Concat(series.Metadata.Genres.Select(g => g.Title));
+                var updatedRating = ExternalMetadataService.DetermineAgeRating(allTags, settings.AgeRatingMappings);
+                if (updatedRating > series.Metadata.AgeRating)
```
Comment (majora2007) [inline API/Services/Tasks/Scanner/ProcessSeries.cs:319]: This doesn't seem correct. If I had a rule that "action" was "M", then removed it, next scan would not update the age rating because previous run had M.

File: API/Services/Tasks/Scanner/ProcessSeries.cs [hunk 4]
```diff
@@ -1069,16 +1072,31 @@ private async Task UpdateChapterFromComicInfo(Chapter chapter, ComicInfo? comicI
...
+            {
+                ExternalMetadataService.GenerateGenreAndTagLists(genres, tags, settings, ref finalTags, ref finalGenres);
+            }
+            else
+            {
+                finalGenres.AddRange(genres);
+                finalTags.AddRange(tags);
+            }
+
+            if (!chapter.GenresLocked)
```
Comment (majora2007) [inline API/Services/Tasks/Scanner/ProcessSeries.cs:1083]: You need {} on if statements that aren't jumps (continue/return)

File: API/Services/Tasks/ScannerService.cs [hunk 5]
```diff
@@ -641,19 +645,33 @@ private async Task<int> ProcessParsedSeries(bool forceUpdate, Dictionary<ParsedS
...
+                .Distinct().ToList();
 
             var allTags = toProcess
                 .SelectMany(s => s.Value
                     .SelectMany(p => p.ComicInfo?.Tags?
                                          .Split(",", StringSplitOptions.RemoveEmptyEntries) // Split on comma and remove empty entries
                                          .Select(g => g.Trim()) // Trim each genre
                                          .Where(g => !string.IsNullOrWhiteSpace(g)) // Ensure no null/empty genres
-                                     ?? [])); // Handle null Tag or ComicInfo safely
+                                     ?? []))  // Handle null Tag or ComicInfo safely
```
Comment (majora2007) [inline API/Services/Tasks/ScannerService.cs]: Remove comment

File: API/Services/Tasks/ScannerService.cs [hunk 6]
```diff
@@ -641,19 +645,33 @@ private async Task<int> ProcessParsedSeries(bool forceUpdate, Dictionary<ParsedS
...
+                .Distinct().ToList();
+
+            var processedGenres = new List<string>();
+            var processedTags = new List<string>();
+
+            if (settings.EnableExtendedMetadataProcessing)
+            {
+                ExternalMetadataService.GenerateGenreAndTagLists(allGenres, allTags, settings, ref processedTags, ref processedGenres);
```
Comment (majora2007) [inline API/Services/Tasks/ScannerService.cs]: I wonder why this doesn't use an out instead of ref and just do the if/else logic within it? Since you basically copy/paste this block in multiple places.

File: UI/Web/src/app/admin/import-mappings/import-mappings.component.html [hunk 7]
```diff
@@ -0,0 +1,171 @@
...
+            <form class="row" [formGroup]="importSettingsForm">
+
+              @if (res.ageRatingConflicts.length > 0) {
+                <div class="conflict-group-title">{{t('age-ratings-label')}}</div>
+                <div class="text-muted">{{t('age-ratings-conflicts-tooltip')}}</div>
+              }
+
+              @for (arm of res.ageRatingConflicts; track arm) {
+                <div class="col-md-6 col-sm-12 pt-4">
+                  @if (importSettingsForm.get('ageRatingConflictResolutions.'+arm); as control) {
```
Comment (majora2007) [inline UI/Web/src/app/admin/import-mappings/import-mappings.component.html]: Spacing around +

File: UI/Web/src/app/admin/import-mappings/import-mappings.component.ts [hunk 8]
```diff
@@ -0,0 +1,308 @@
...
+  steps: TimelineStep[] = [
+    {title: translate('import-mappings.import-step'), index: Step.Import, active: true, icon: 'fa-solid fa-file-arrow-up'},
+    {title: translate('import-mappings.configure-step'), index: Step.Configure, active: false, icon: 'fa-solid fa-gears'},
+    {title: translate('import-mappings.conflicts-step'), index: Step.Conflicts, active: false, icon: 'fa-solid fa-hammer'},
+    {title: translate('import-mappings.finalize-step'), index: Step.Finalize, active: false, icon: 'fa-solid fa-floppy-disk'},
+  ];
+  currentStepIndex = signal(this.steps[0].index);
+
+  fileUploadControl = new FormControl<undefined | Array<File>>(undefined, [
+    FileUploadValidators.accept(['.json']), FileUploadValidators.filesLimit(1)
```
Comment (majora2007) [inline UI/Web/src/app/admin/import-mappings/import-mappings.component.ts:90]: This is nice, can you backport this accept to my cbl import?

File: UI/Web/src/app/admin/import-mappings/import-mappings.component.ts [hunk 9]
```diff
@@ -0,0 +1,308 @@
...
+  importResult = signal<FieldMappingsImportResult | undefined>(undefined);
+
+  ngOnInit(): void {
+    this.settingsService.getMetadataSettings().subscribe((settings) => {
+      this.settings.set(settings);
+    });
+  }
+
+
+  get NextButtonLabel() {
```
Comment (majora2007) [inline UI/Web/src/app/admin/import-mappings/import-mappings.component.ts]: why not make this a computed signal?

File: UI/Web/src/app/admin/import-mappings/import-mappings.component.ts [hunk 10]
```diff
@@ -0,0 +1,308 @@
...
+        this.router.navigate(['settings'], { fragment: fragment });
+      }
+    });
+  }
+
+  async tryImport() {
+    const data = this.importedMappings();
+    if (!data) {
+      this.toastr.error(translate('import-mappings.file-no-valid-content'));
+      return Promise.resolve();
```
Comment (majora2007) [inline UI/Web/src/app/admin/import-mappings/import-mappings.component.ts:206]: Shouldn't this be an observable?

File: UI/Web/src/app/admin/import-mappings/import-mappings.component.ts [hunk 11]
```diff
@@ -0,0 +1,308 @@
...
+      this.toastr.error(translate('import-mappings.invalid-file'));
+      return;
+    }
+    if (!newImport.fieldMappings && !newImport.ageRatingMappings && !newImport.blacklist && !newImport.whitelist) {
+      this.toastr.error(translate('import-mappings.file-no-valid-content'));
+      return;
+    }
+
+    this.importedMappings.set(newImport);
+    this.currentStepIndex.update(x=>x+1);
```
Comment (majora2007) [inline UI/Web/src/app/admin/import-mappings/import-mappings.component.ts]: Spacing

File: UI/Web/src/app/admin/import-mappings/import-mappings.component.ts [hunk 12]
```diff
@@ -0,0 +1,308 @@
...
+    if (this.currentStepIndex() === Step.Finalize) {
+      if (this.importResult()!.ageRatingConflicts.length === 0) {
+        this.currentStepIndex.set(Step.Configure);
+      } else {
+        this.currentStepIndex.set(Step.Conflicts);
+      }
+      return;
+    }
+
+    this.currentStepIndex.update(x => x-1);
```
Comment (majora2007) [inline UI/Web/src/app/admin/import-mappings/import-mappings.component.ts]: spaces around -

File: UI/Web/src/app/admin/import-mappings/import-mappings.component.ts [hunk 13]
```diff
@@ -0,0 +1,308 @@
...
+
+    // Reset when returning to the first step
+    if (this.currentStepIndex() === Step.Import) {
+      this.fileUploadControl.reset();
+      (this.importSettingsForm.get('ageRatingConflictResolutions') as FormArray).clear();
+    }
+
+  }
+
+  canMoveToNextStep() {
```
Comment (majora2007) [inline UI/Web/src/app/admin/import-mappings/import-mappings.component.ts]: This should be a computed signal

File: UI/Web/src/app/admin/import-mappings/import-mappings.component.ts [hunk 14]
```diff
@@ -0,0 +1,308 @@
...
+      case Step.Configure:
+        return true;
+      case Step.Conflicts:
+        return this.importSettingsForm.valid;
+      default:
+          return false;
+    }
+  }
+
+  isFileSelected() {
```
Comment (majora2007) [inline UI/Web/src/app/admin/import-mappings/import-mappings.component.ts:297]: computed signal

File: UI/Web/src/app/admin/import-mappings/import-mappings.component.ts [hunk 15]
```diff
@@ -0,0 +1,308 @@
...
+    const files = this.uploadForm.get('files')?.value;
+    return files && files.length === 1;
+  }
+
+  canMoveToPrevStep() {
```
Comment (majora2007) [inline UI/Web/src/app/admin/import-mappings/import-mappings.component.ts]: computed signal

File: UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.html [hunk 16]
```diff
@@ -0,0 +1,148 @@
...
+            @for (ageRating of ageRatings(); track ageRating.value) {
+              <option [value]="ageRating.value">
+                {{ageRating.value | ageRating}}
+              </option>
+            }
+          </select>
+        </div>
+        <div class="col-md-2">
+          <button class="btn btn-icon" (click)="removeAgeRatingMappingRow(i)">
+            <i class="fa fa-trash-alt" aria-hidden="true"></i>
```
Comment (majora2007) [inline UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.html:73]: You need a span class=visibiliy-hidden to tell the user (screen reader) this is a remove button. 

You need the button to aria-labelledby="id of the str value"

File: UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.html [hunk 17]
```diff
@@ -0,0 +1,148 @@
...
+          </button>
+
+          @if($last) {
+            <button class="btn btn-icon" (click)="addAgeRatingMapping()">
```
Comment (majora2007) [inline UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.html]: Need the same accessibility span to tell that this is new age rating mapping. You could alternatively labelledby=id of ('age-rating-mapping-title') header.

File: UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.html [hunk 18]
```diff
@@ -0,0 +1,148 @@
...
+              <i class="fa fa-plus" aria-hidden="true"></i>
+            </button>
+          }
+        </div>
+      </div>
+    } @empty {
+      <button class="btn btn-secondary" (click)="addAgeRatingMapping()">
```
Comment (majora2007) [inline UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.html]: Same as above.

File: UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.html [hunk 19]
```diff
@@ -0,0 +1,148 @@
...
+        </div>
+        <div class="col-md-2">
+          <select class="form-select" formControlName="destinationType">
+            <option [value]="MetadataFieldType.Genre">{{t('genre')}}</option>
+            <option [value]="MetadataFieldType.Tag">{{t('tag')}}</option>
+          </select>
+        </div>
+        <div class="col-md-2">
+          <input type="text" class="form-control" formControlName="destinationValue"
+                 placeholder="Destination genre/tag" />
```
Comment (majora2007) [inline UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.html]: localization

File: UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.html [hunk 20]
```diff
@@ -0,0 +1,148 @@
...
+      <div [formGroupName]="i" class="row mb-2">
+        <div class="col-md-2">
+          <select class="form-select" formControlName="sourceType">
+            <option [value]="MetadataFieldType.Genre">{{t('genre')}}</option>
+            <option [value]="MetadataFieldType.Tag">{{t('tag')}}</option>
+          </select>
+        </div>
+        <div class="col-md-2">
+          <input type="text" class="form-control" formControlName="sourceValue"
+                 placeholder="Source genre/tag" />
```
Comment (majora2007) [inline UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.html]: localization

File: UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.html [hunk 21]
```diff
@@ -0,0 +1,148 @@
...
+          @if ($last) {
+            <button class="btn btn-icon" (click)="addFieldMapping()">
+              <i class="fa fa-plus" aria-hidden="true"></i>
+            </button>
+          }
+        </div>
+      </div>
+    } @empty {
+      <button class="btn btn-secondary" (click)="addFieldMapping()">
+        <i class="fa fa-plus" aria-hidden="true"></i> {{t('add-field-mapping-label')}}
```
Comment (majora2007) [inline UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.html]: Use me-1 instead of a space

File: UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.scss [hunk 22]
```diff
@@ -0,0 +1,3 @@
+.text-muted {
+  font-size: 14px;
```
Comment (majora2007) [inline UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.scss]: Use rem whenever possible

File: UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.ts [hunk 23]
```diff
@@ -0,0 +1,173 @@
...
+    DefaultValuePipe,
+    FormsModule,
+    ReactiveFormsModule,
+    SettingItemComponent,
+    TagBadgeComponent,
+    TranslocoDirective,
+    SettingSwitchComponent
+  ],
+  templateUrl: './manage-metadata-mappings.component.html',
+  styleUrl: './manage-metadata-mappings.component.scss'
```
Comment (majora2007) [inline UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.ts]: You're missing ChangeDetection onPush

File: UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.ts [hunk 24]
```diff
@@ -0,0 +1,167 @@
...
+
+    return [];
+  }
+
+  public packData(): MetadataMappingsExport {
+    const ageRatingMappings = this.ageRatingMappings.controls.reduce((acc, control) => {
+      // @ts-ignore
+      const { str, rating } = control.value;
+      if (str && rating) {
+        // @ts-ignore
```
[the remark this answers is not in the document]
Comment (majora2007) [reply UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.ts]: Agree on these, let's avoid ts-ignore and use casting instead.

File: UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.ts [hunk 25]
```diff
@@ -0,0 +1,173 @@
...
+    return {
+      ageRatingMappings: ageRatingMappings,
+      fieldMappings: fieldMappings,
+      blacklist: blacklist,
+      whitelist: whitelist,
+    }
+  }
+
+  export() {
+    const data = this.packData();
```
Comment (majora2007) [inline UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.ts:130]: We have a download service, let's re-use that.

File: UI/Web/src/app/admin/manage-metadata-settings/manage-metadata-settings.component.html [hunk 26]
```diff
@@ -6,17 +6,50 @@
...
+        <div class="col-md-6 col-sm-12">
+          <button class="btn btn-secondary" (click)="manageMetadataMappingsComponent.export()">
+            {{ t('export-settings') }}
+          </button>
+          <div class="text-muted mt-2">{{t('export-tooltip')}}</div>
+        </div>
+
+        <div class="col-md-6 col-sm-12">
+          <button class="btn btn-secondary" routerLink="/settings" [fragment]="SettingsTabId.MappingsImport">
+            {{ t('import-settings') }}
```
Comment (majora2007) [inline UI/Web/src/app/admin/manage-metadata-settings/manage-metadata-settings.component.html]: I don't personally like spaces with {{ }}, but i'm indifferent to it.

File: UI/Web/src/app/admin/manage-public-metadata-settings/manage-public-metadata-settings.component.html [hunk 27]
```diff
@@ -0,0 +1,45 @@
+
```
Comment (majora2007) [inline UI/Web/src/app/admin/manage-public-metadata-settings/manage-public-metadata-settings.component.html]: Remove this empty line

File: UI/Web/src/app/admin/manage-public-metadata-settings/manage-public-metadata-settings.component.html [hunk 28]
```diff
@@ -0,0 +1,45 @@
...
+          </ng-template>
+        </app-setting-switch>
+      }
+    </div>
+  </form>
+
+  <div class="row g-0 mt-4 mb-4">
+    <div class="col-md-6 col-sm-12">
+      <button class="btn btn-secondary" (click)="manageMetadataMappingsComponent.export()">
+        {{ t('export-settings') }}
```
Comment (majora2007) [inline UI/Web/src/app/admin/manage-public-metadata-settings/manage-public-metadata-settings.component.html:24]: Another nitpick. It's better to have it the same across all the code.

**Review by majora2007 — CHANGES_REQUESTED** [review]

File: API/Services/Tasks/Scanner/ProcessSeries.cs (hunk 3 above)
Comment (Fesaa) [reply API/Services/Tasks/Scanner/ProcessSeries.cs:319]: image

The AgeRating here is the one from comic info, so this shouldn't be an issue. Don't want to lower it if you've set a lower on disk

File: API/Services/Tasks/ScannerService.cs (hunk 6 above)
Comment (Fesaa) [reply API/Services/Tasks/ScannerService.cs]: Good call, the original code used ref. I did not think further. I've written a wrapper around this method to include the if else block. Is much nicer

File: UI/Web/src/app/admin/import-mappings/import-mappings.component.ts (hunk 10 above)
Comment (Fesaa) [reply UI/Web/src/app/admin/import-mappings/import-mappings.component.ts:206]: The code was a lot easier to write and read with standard async/await and interop to it from rxjs than the other way around, as we call an async method on file. (In the context of where this method is called)

So it's not needed (the observable down the line is wrapped in firstValueFrom)

File: UI/Web/src/app/admin/import-mappings/import-mappings.component.ts (hunk 14 above)
Comment (Fesaa) [reply UI/Web/src/app/admin/import-mappings/import-mappings.component.ts:297]: There are no signals used in this method, it won't get recomputed. The method is only called in the ts code, so it's not needed anyway

File: UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.ts (hunk 23 above)
Comment (Fesaa) [reply UI/Web/src/app/admin/manage-metadata-mappings/manage-metadata-mappings.component.ts]: I've added it in the schematics so angular will auto add it when creating a new component.

File: UI/Web/src/app/reading-list/_components/import-cbl/import-cbl.component.ts [hunk 29]
```diff
@@ -76,7 +76,7 @@ export class ImportCblComponent {
 
 
   fileUploadControl = new FormControl<undefined | Array<File>>(undefined, [
-    FileUploadValidators.accept(['.cbl']),
+    FileUploadValidators.accept(['.cbl']), FileUploadValidators.filesLimit(1)
```
Comment (majora2007) [inline UI/Web/src/app/reading-list/_components/import-cbl/import-cbl.component.ts]: You need to remove this, cbl is bulk, so there is not limit

**Review by majora2007 — APPROVED** [review]
