### PR TITLE
A few bug fixes

### LINKED ISSUE #3089: Webtoon goes to next chapter if images don't load while scrolling
### What happened?

When reading a webtoon in continuous scroll mode, if Kavita is running slow or the Internet is slow and an image doesn't load by the time you reach the end of a chapter, you can trigger the "next chapter" scroll pull down.

### What did you expect?

The expected behavior would be for the "next chapter" scroll only be available after the final image. Any missing images should have a height buffer already loaded that way there is a gap while an image loads. 
The height doesn't have to be perfect, but it does need to be greater than 0. This way, you can stop when a page is loading.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

### Relevant log output

_No response_

### Additional Notes

_No response_

### LINKED ISSUE #3754: Safari - Manga slider not reflecting number
### What happened?

Progress in vertical scrolling on iPad OS is not captured when leaving an issue part way through.

### What did you expect?

When leaving an issue part way through, on return it should take me to the same place like it does on a desktop browser like Chrome.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.6.1 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome and Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Safari and Chrome

### Relevant log output

```shell
It’s clear the tracking isn’t working as the pop up progress shows page 1 no matter how far through the issue you go.
```

### Additional Notes

I don’t think it’s a server issue as tracking works as expected on a desktop browser in Windows.

### LINKED ISSUE #3925: Add max retry count for checking server update
### What happened?

I am experiencing trouble in connecting the server to get an update, and the service is continuously retrying causing a consistent CPU usage, it should for a max number of times and then trigger again at the scheduled time.

### What did you expect?

Th service should stop checking for updates after a while.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.7 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell
[Kavita] [2025-07-14 20:02:08.731 +01:00  19] [Error] Hangfire.AutomaticRetryAttribute Failed to process the job '4': an exception occurred.
Flurl.Http.FlurlHttpTimeoutException: Call timed out: GET https://api.github.com/repos/Kareadita/Kavita/releases/latest
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlClient.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at API.Services.Tasks.VersionUpdaterService.GetGithubRelease() in /home/runner/work/Kavita/Kavita/API/Services/Tasks/VersionUpdaterService.cs:line 539
   at API.Services.Tasks.VersionUpdaterService.CheckForUpdate() in /home/runner/work/Kavita/Kavita/API/Services/Tasks/VersionUpdaterService.cs:line 105
   at API.Services.TaskScheduler.CheckForUpdate() in /home/runner/work/Kavita/Kavita/API/Services/TaskScheduler.cs:line 490
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
[Kavita] [2025-07-15 00:01:43.489 +01:00  19] [Error] Hangfire.AutomaticRetryAttribute Failed to process the job '5': an exception occurred.
```

### Additional Notes

_No response_

### LINKED ISSUE #3935: Baseurl not populating on from reading list
### What happened?

When selecting a series from a reading list it does not honor the base url option. 
When redirecting it causes a 404 error that is resolved when manually adding back the baseurl.

Steps to replicate is to have a comic in a reading list and have a base url configured on the site.  
Navigate to the reading list and attempt to go to the series by clicking the name from one of the issues.
Error should occur here.

### What did you expect?

I would expect the base url to be used in all locations on the server

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.7 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
404 page not found
```

### Additional Notes

_No response_

### LINKED ISSUE #3958: Kavita+ Eligible badge missing for comics libraries
### What happened?

Now that comics libraries have metadata support they should have the Kavita+ eligible badge on the library type selection like manga/light novels

### What did you expect?

Comics and comics (legacy) libraries have the Kavita+ eligible badge on type selection

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### LINKED ISSUE #3960: Favicons download fail pointing to https://www.kavitareader.com/CoversDB/favicons/publishers.txt
### What happened?

favicons do not appear to be downloading and there is an error that appears pointing to https://www.kavitareader.com/CoversDB/favicons/publishers.txt
in CoverDbService.cs it does have publishers.txt as the urlsFileName but i believe it should be urls.txt

### What did you expect?

kavita is able to download favicons from the repo as a fallback when it can't get favicons from the site itself

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.7 - Stable

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

_No response_

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by Fesaa**
# Changed
- Changed: If OIDC sync is enabled, logging in will now trigger the sync (develop)
- Changed: Show K+ eligible badge for all libraries that have at least K+ metadata (Closes #3958)

# Fixed
- Fixed: Fixed the OIDC discovery document being loaded on each token refresh (develop)
- Fixed: Fixed non OIDC user being synced when OIDC sync is enabled (develop)
- Fixed: Fixed newly created reading profiles sometimes saving twice
- Fixed: Fixed the base url setting not being respected in some places (Fixes #3935)
- Fixed: Fixed page not updating in the webtoon scroller in Safari (Fixes #3754)
- Fixed: Fixed CheckUpdate getting stuck in a loop if GitHub can't be reached (Fixes #3925)
- Fixed: Fixed favicons not downloading from CoverDB (Fixes #3960)
- Fixed: Fixed the webtoon reader skipping chapters while scroller if images load slowly (Fixes #3089)
- Fixed: Fixed age rating mappings not working if any keys were equal (when normalized) (develop)

### CODE REVIEW

File: API/Helpers/TaskHelper.cs [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+
+    /// <summary>
+    /// Wrap a simple action in a retry mechanism. Allowing up to <see cref="maxAttempts"/> attamps, with at least
+    /// <see cref="baseDelay"/> between each attempt
+    /// </summary>
+    /// <param name="logger"></param>
+    /// <param name="action"></param>
+    /// <param name="maxAttempts"></param>
+    /// <param name="baseDelay">Base delay in ms</param>
+    public static async Task WithRetry(ILogger logger, Func<Task> action, int maxAttempts, int baseDelay)
```
Comment (majora2007) [inline API/Helpers/TaskHelper.cs]: Can we investigate Polly over a custom implementation?

File: API/Helpers/TaskHelper.cs [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+        for (var attempt = 0; attempt < maxAttempts; attempt++)
+        {
+            try
+            {
+                await action();
+                return;
+            }
+            catch (Exception e)
+            {
+                logger.LogWarning(e, "An exception occured running task {Attempt}/{MaxAttemps}", attempt+1,maxAttempts);
```
Comment (majora2007) [inline API/Helpers/TaskHelper.cs]: Spacing

File: .github/copilot-instructions.md [hunk 3]
```diff
@@ -0,0 +1,17 @@
+﻿## Coding Guidelines
```
Comment (majora2007) [inline .github/copilot-instructions.md:1]: Add a rule that operations (+, -, , etc) should all have spaces around them (`a + b`) not `a+b`. 

Add a rule that there should always be a space after a comma.

File: API/Services/OidcService.cs [hunk 4]
```diff
@@ -565,10 +580,10 @@ private async Task SyncAgeRestriction(OidcConfigDto settings, ClaimsPrincipal cl
     /// <param name="refreshToken"></param>
     /// <returns></returns>
     /// <exception cref="InvalidOperationException"></exception>
-    private async Task<OpenIdConnectMessage> RefreshTokenAsync(OidcConfigDto dto, string refreshToken)
+    private static async Task<OpenIdConnectMessage> RefreshTokenAsync(OidcConfigDto dto, string refreshToken)
     {
 
-        _discoveryDocument ??= await LoadOidcConfiguration(dto.Authority);
+        DiscoveryDocument ??= await LoadOidcConfiguration(dto.Authority);
```
Comment (majora2007) [inline API/Services/OidcService.cs]: This needs to be locked to avoid concurrency issues.

File: UI/Web/src/app/manga-reader/_components/infinite-scroller/infinite-scroller.component.ts [hunk 5]
```diff
@@ -220,14 +220,29 @@ export class InfiniteScrollerComponent implements OnInit, OnChanges, OnDestroy,
...
+      .subscribe((event) => {
+        this.handleScrollEvent(event)
+      });
+
+    const isScrollEndSupported = 'onscrollend' in document;
+    if (isScrollEndSupported) {
+      fromEvent(element, 'scrollend')
+        .pipe(debounceTime(20), takeUntilDestroyed(this.destroyRef))
+        .subscribe((event) => {
+          this.handleScrollEndEvent(event)
```
Comment (majora2007) [inline UI/Web/src/app/manga-reader/_components/infinite-scroller/infinite-scroller.component.ts]: Move this into a tap and keep subscribe empty. This is the "best approach" i learned after this code was written.

File: UI/Web/src/app/manga-reader/_components/infinite-scroller/infinite-scroller.component.ts [hunk 6]
```diff
@@ -220,14 +220,29 @@ export class InfiniteScrollerComponent implements OnInit, OnChanges, OnDestroy,
...
+    fromEvent(element, 'scroll')
+      .pipe(debounceTime(20), takeUntilDestroyed(this.destroyRef))
+      .subscribe((event) => {
+        this.handleScrollEvent(event)
+      });
+
+    const isScrollEndSupported = 'onscrollend' in document;
+    if (isScrollEndSupported) {
+      fromEvent(element, 'scrollend')
+        .pipe(debounceTime(20), takeUntilDestroyed(this.destroyRef))
```
Comment (majora2007) [inline UI/Web/src/app/manga-reader/_components/infinite-scroller/infinite-scroller.component.ts]: Don't hardcode magic numbers. Put this in a const above the class with a descriptive name.

File: UI/Web/src/app/manga-reader/_components/infinite-scroller/infinite-scroller.component.ts [hunk 7]
```diff
@@ -220,14 +220,29 @@ export class InfiniteScrollerComponent implements OnInit, OnChanges, OnDestroy,
...
-    .pipe(debounceTime(20), takeUntilDestroyed(this.destroyRef))
-    .subscribe((event) => this.handleScrollEndEvent(event));
+    fromEvent(element, 'scroll')
+      .pipe(debounceTime(20), takeUntilDestroyed(this.destroyRef))
+      .subscribe((event) => {
+        this.handleScrollEvent(event)
+      });
+
+    const isScrollEndSupported = 'onscrollend' in document;
+    if (isScrollEndSupported) {
```
Comment (majora2007) [inline UI/Web/src/app/manga-reader/_components/infinite-scroller/infinite-scroller.component.ts]: Don't duplicate the logic, just change the string we build the fromEvent from.

File: UI/Web/src/app/user-settings/manage-reading-profiles/manage-reading-profiles.component.ts [hunk 8]
```diff
@@ -219,41 +221,50 @@ export class ManageReadingProfilesComponent implements OnInit {
...
       takeUntilDestroyed(this.destroyRef),
-      tap(_ => this.autoSave()),
+      tap(_ => this.savingProfile.set(true)),
+      switchMap(_ => this.autoSave()),
+      finalize(() => this.savingProfile.set(false))
     ).subscribe();
   }
 
+  /**
+   * Autosave will not error
```
Comment (majora2007) [inline UI/Web/src/app/user-settings/manage-reading-profiles/manage-reading-profiles.component.ts]: What does this comment mean if we are using catchError?

File: UI/Web/src/app/user-settings/user-holds/scrobbling-holds.component.html [hunk 9]
```diff
@@ -17,7 +17,7 @@
       </ng-template>
       <ng-template let-item="row" ngx-datatable-cell-template>
         <app-image [width]="'32px'" [height]="'32px'" [imageUrl]="imageService.getSeriesCoverImage(item.seriesId)"></app-image>
-        <a class="btn-link ms-2" href="/library/{{item.libraryId}}/series/{{item.seriesId}}" target="_blank">{{item.seriesName}}</a>
+        <a class="btn-link ms-2" href="{{baseUrl}}library/{{item.libraryId}}/series/{{item.seriesId}}" target="_blank">{{item.seriesName}}</a>
```
Comment (majora2007) [inline UI/Web/src/app/user-settings/user-holds/scrobbling-holds.component.html:20]: We should add a copilot rule to ensure any hrefs start with baseUrl

**Review by majora2007 — CHANGES_REQUESTED** [review]

File: UI/Web/src/app/user-settings/manage-reading-profiles/manage-reading-profiles.component.ts (hunk 8 above)
Comment (Fesaa) [reply UI/Web/src/app/user-settings/manage-reading-profiles/manage-reading-profiles.component.ts]: That the method itself will not throw errors / handle them safely. Means it's safe to set the signal back to false above

File: UI/Web/src/app/manga-reader/_components/infinite-scroller/infinite-scroller.component.ts (hunk 5 above)
Comment (Fesaa) [reply UI/Web/src/app/manga-reader/_components/infinite-scroller/infinite-scroller.component.ts]: I'm curious what the reason behind this is

Comment (majora2007) [reply UI/Web/src/app/manga-reader/_components/infinite-scroller/infinite-scroller.component.ts]: I think because everything is within the pipe.

File: UI/Web/src/app/user-settings/manage-reading-profiles/manage-reading-profiles.component.ts (hunk 8 above)
Comment (majora2007) [reply UI/Web/src/app/user-settings/manage-reading-profiles/manage-reading-profiles.component.ts]: I would elaborate more. It's not clear the intent of the comment and leads to confusion.

File: API/Services/OidcService.cs [hunk 10]
```diff
@@ -631,18 +634,37 @@ private static async Task<ClaimsPrincipal> ParseIdToken(OidcConfigDto dto, strin
...
+        await _discoveryDocumentSemaphore.WaitAsync();
+        try
+        {
+            // Double check that the document hasn't become available
+            if (_discoveryDocument != null)
+            {
+                return _discoveryDocument;
+            }
+
+            var hasTrailingSlash = authority.EndsWith('/');
```
Comment (majora2007) [inline API/Services/OidcService.cs]: I don't see you ever setting or accessing _discoveryDocument within the lock

File: UI/Web/src/app/admin/manage-users/manage-users.component.html [hunk 11]
```diff
@@ -25,10 +25,10 @@
             <div class="d-flex flex-row justify-content-center align-items-center">
               @switch (member.identityProvider) {
                 @case (IdentityProvider.OpenIdConnect) {
-                  <app-image imageUrl="assets/icons/open-id-connect-logo.svg" height="16px" width="16px"></app-image>
+                  <app-image [ngbTooltip]="t('oidc')" imageUrl="assets/icons/open-id-connect-logo.svg" height="16px" width="16px"></app-image>
```
Comment (majora2007) [inline UI/Web/src/app/admin/manage-users/manage-users.component.html]: key should be identity-provider-oidc-tooltip

File: UI/Web/src/app/admin/manage-users/manage-users.component.html [hunk 12]
```diff
@@ -25,10 +25,10 @@
...
                 }
                 @case (IdentityProvider.Kavita) {
-                  <app-image imageUrl="assets/icons/favicon-16x16.png" height="16px" width="16px"></app-image>
+                  <app-image [ngbTooltip]="t('native')" imageUrl="assets/icons/favicon-16x16.png" height="16px" width="16px"></app-image>
```
Comment (majora2007) [inline UI/Web/src/app/admin/manage-users/manage-users.component.html]: key should be identity-provider-native-tooltip

File: UI/Web/src/app/manga-reader/_components/infinite-scroller/infinite-scroller.component.ts [hunk 13]
```diff
@@ -179,6 +179,15 @@ export class InfiniteScrollerComponent implements OnInit, OnChanges, OnDestroy,
    */
   debugLogFilter: Array<string> = ['[PREFETCH]', '[Intersection]', '[Visibility]', '[Image Load]'];
 
+  /**
+   * Default debounce time from scroll and scrollend event listeners
+   */
+  defaultScrollDebounce = 20;
```
Comment (majora2007) [inline UI/Web/src/app/manga-reader/_components/infinite-scroller/infinite-scroller.component.ts]: Make these const, which means outside the class. They go above the class declaration.

File: UI/Web/src/app/manga-reader/_components/infinite-scroller/infinite-scroller.component.ts [hunk 14]
```diff
@@ -223,26 +232,24 @@ export class InfiniteScrollerComponent implements OnInit, OnChanges, OnDestroy,
     const element = this.isFullscreenMode ? this.readerElemRef.nativeElement : this.document.body;
 
     fromEvent(element, 'scroll')
-      .pipe(debounceTime(20), takeUntilDestroyed(this.destroyRef))
-      .subscribe((event) => {
-        this.handleScrollEvent(event)
-      });
+      .pipe(
```
Comment (majora2007) [inline UI/Web/src/app/manga-reader/_components/infinite-scroller/infinite-scroller.component.ts:234]: The original code has scrollend calling handleScrollEndEvent(), your new code has them both calling handleScrollEvent

**Review by majora2007 — CHANGES_REQUESTED** [review]

File: UI/Web/src/app/user-settings/manage-reading-profiles/manage-reading-profiles.component.ts [hunk 15]
```diff
@@ -219,41 +221,46 @@ export class ManageReadingProfilesComponent implements OnInit {
...
-            return newProfile;
-          });
-          this.cdRef.markForCheck();
-        },
-        error: err => {
-          console.log(err);
-          this.toastr.error(err.message);
-        }
-      })
+          return of(null);
```
[the remark this answers is not in the document]
Comment (Fesaa) [reply UI/Web/src/app/user-settings/manage-reading-profiles/manage-reading-profiles.component.ts:245]: The return value isn't actually used, it just needs to be an observable to fit in the pipe

File: UI/Web/src/app/user-settings/manage-reading-profiles/manage-reading-profiles.component.ts [hunk 16]
```diff
@@ -219,41 +221,46 @@ export class ManageReadingProfilesComponent implements OnInit {
...
+        this.readingProfiles = this.readingProfiles.map(p => {
+          if (p.id !== profile.id) return p;
+          return newProfile;
+        });
+        this.cdRef.markForCheck();
+      }),
+      catchError(err => {
+        console.log(err);
+        this.toastr.error(err.message);
+        return of(null);
```
[the remark this answers is not in the document]
Comment (Fesaa) [reply UI/Web/src/app/user-settings/manage-reading-profiles/manage-reading-profiles.component.ts:264]: The return value isn't actually used, it just needs to be an observable to fit in the pipe

File: API/Services/Plus/ExternalMetadataService.cs [hunk 17]
```diff
@@ -1806,10 +1806,15 @@ public static AgeRating DetermineAgeRating(IEnumerable<string> values, Dictionar
...
+        mappings = mappings
+            .GroupBy(m => m.Key.ToNormalized())
+            .ToDictionary(
+                g => g.Key,
+                g => g.Max(m => m.Value)
+            );
 
         return values
-            .Select(v => mappings.TryGetValue(v.ToNormalized(), out var mapping) ? mapping : AgeRating.Unknown)
+            .Select(v => mappings.GetValueOrDefault(v.ToNormalized(), AgeRating.Unknown))
```
[the remark this answers is not in the document]
Comment (Fesaa) [reply API/Services/Plus/ExternalMetadataService.cs:1817]: Yes, each value is normalized once, as well as each key in the dictionary. This is correct

File: UI/Web/src/app/user-settings/manage-reading-profiles/manage-reading-profiles.component.ts (hunk 16 above)
[the remark this answers is not in the document]
Comment (majora2007) [reply UI/Web/src/app/user-settings/manage-reading-profiles/manage-reading-profiles.component.ts:264]: I guess this can't detect the lack of newline above the return. You have multiple cases of this in the PR.

File: API/Services/OidcService.cs [hunk 18]
```diff
@@ -68,7 +69,9 @@ public class OidcService(ILogger<OidcService> logger, UserManager<AppUser> userM
     /// The name of the Auth Cookie set by .NET
     public const string CookieName = ".AspNetCore.Cookies";
 
-    private OpenIdConnectConfiguration? _discoveryDocument;
+    private static OpenIdConnectConfiguration? _discoveryDocument;
+    private static readonly SemaphoreSlim _discoveryDocumentSemaphore = new(1, 1);
```
[the remark this answers is not in the document]
Comment (Fesaa) [reply API/Services/OidcService.cs]: There will only ever be one authority, this won't be a problem. We're also not unit testing anything with the document directly.

File: UI/Web/src/app/user-settings/manage-reading-profiles/manage-reading-profiles.component.ts (hunk 16 above)
[the remark this answers is not in the document]
Comment (Fesaa) [reply UI/Web/src/app/user-settings/manage-reading-profiles/manage-reading-profiles.component.ts:264]: Maybe it only works once the document in the main branch? I'll find the missing newlines

**Review by majora2007 — APPROVED** [review]
