### PR TITLE
Fixed cover size when uploading custom covers

### LINKED ISSUE #2807: Custom Covers, dont properly work.
### What happened?

If i upload a custom cover, the "Cover Image Size" gets completly ignored.
Instead Kavita generates an 225 x 320 blurry Image, the automatically converted / generated Covers are completly fine.
Original:
Shounen Chotto Sabotteko
Kavitas Result on Cover Size Large:
series2

### What did you expect?

That my Covers i manually upload, get converted to the same size or get shrinked to my set Cover Image Size.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (LS.IO)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Dont see anything regarding the conversion in the logs, but here are they anways:

[Kavita] [2024-03-21 07:21:05.934 +00:00  34] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /library/1/series/4 responded 200 in 0.6261 ms
[Kavita] [2024-03-21 07:21:06.212 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 0.9481 ms
[Kavita] [2024-03-21 07:21:06.215 +00:00  30] [Debug] API.Controllers.LibraryController Caching libraries for library_Elry
[Kavita] [2024-03-21 07:21:06.216 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library responded 200 in 1.3387 ms
[Kavita] [2024-03-21 07:21:06.217 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/device responded 200 in 0.5606 ms
[Kavita] [2024-03-21 07:21:06.218 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 0.2100 ms
[Kavita] [2024-03-21 07:21:06.220 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/users/has-library-access?libraryId=1 responded 200 in 0.7142 ms
[Kavita] [2024-03-21 07:21:06.223 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/stream/sidenav?visibleOnly=true responded 200 in 2.2614 ms
[Kavita] [2024-03-21 07:21:06.410 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 0.6699 ms
[Kavita] [2024-03-21 07:21:06.424 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme/download-content?themeId=2 responded 200 in 1.5395 ms
[Kavita] [2024-03-21 07:21:06.495 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/metadata?seriesId=4 responded 200 in 5.1912 ms
[Kavita] [2024-03-21 07:21:06.496 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/want-to-read?seriesId=4 responded 200 in 0.9472 ms
[Kavita] [2024-03-21 07:21:06.498 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/readinglist/lists-for-series?seriesId=4 responded 200 in 0.4364 ms
[Kavita] [2024-03-21 07:21:06.498 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/has-progress?seriesId=4 responded 200 in 0.3803 ms
[Kavita] [2024-03-21 07:21:06.502 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/continue-point?seriesId=4 responded 200 in 3.4151 ms
[Kavita] [2024-03-21 07:21:06.503 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library/type?libraryId=1 responded 200 in 0.2718 ms
[Kavita] [2024-03-21 07:21:06.504 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/4 responded 200 in 0.8371 ms
[Kavita] [2024-03-21 07:21:06.700 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/next-expected?seriesId=4 responded 200 in 3.7392 ms
[Kavita] [2024-03-21 07:21:06.717 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/series-detail?seriesId=4 responded 200 in 12.0143 ms
[Kavita] [2024-03-21 07:21:06.721 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/metadata/series-detail-plus?seriesId=4&libraryType=0 responded 200 in 3.7140 ms
[Kavita] [2024-03-21 07:21:06.727 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/all-related?seriesId=4 responded 200 in 5.4010 ms
[Kavita] [2024-03-21 07:21:06.730 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/time-left?seriesId=4 responded 200 in 1.0352 ms
[Kavita] [2024-03-21 07:21:06.732 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/scrobbling/has-hold?seriesId=4 responded 200 in 0.3927 ms
[Kavita] [2024-03-21 07:21:06.733 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/scrobbling/library-allows-scrobbling?seriesId=4 responded 200 in 0.4031 ms
[Kavita] [2024-03-21 07:21:06.734 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/rating/overall?seriesId=4 responded 200 in 0.5366 ms
[Kavita] [2024-03-21 07:21:07.149 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 936.0889 ms
[Kavita] [2024-03-21 07:21:08.778 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 1428.1334 ms
[Kavita] [2024-03-21 07:21:08.846 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/metadata?seriesId=4 responded 200 in 2.4296 ms
[Kavita] [2024-03-21 07:21:08.847 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/metadata/publication-status responded 200 in 0.2742 ms
[Kavita] [2024-03-21 07:21:08.852 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/metadata/all-languages responded 200 in 5.0008 ms
[Kavita] [2024-03-21 07:21:08.853 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/metadata/age-ratings responded 200 in 0.2540 ms
[Kavita] [2024-03-21 07:21:08.858 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/volumes?seriesId=4 responded 200 in 3.8268 ms
[Kavita] [2024-03-21 07:21:21.600 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/metadata responded 200 in 9.2628 ms
[Kavita] [2024-03-21 07:21:21.980 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/upload/series responded 200 in 37.1669 ms
[Kavita] [2024-03-21 07:21:22.182 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/metadata?seriesId=4 responded 200 in 3.5360 ms
[Kavita] [2024-03-21 07:21:22.184 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/want-to-read?seriesId=4 responded 200 in 1.2126 ms
[Kavita] [2024-03-21 07:21:22.189 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/continue-point?seriesId=4 responded 200 in 3.9575 ms
[Kavita] [2024-03-21 07:21:22.191 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/4 responded 200 in 1.0631 ms
[Kavita] [2024-03-21 07:21:22.192 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/readinglist/lists-for-series?seriesId=4 responded 200 in 0.4117 ms
[Kavita] [2024-03-21 07:21:22.193 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/has-progress?seriesId=4 responded 200 in 0.4751 ms
[Kavita] [2024-03-21 07:21:22.388 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/next-expected?seriesId=4 responded 200 in 4.8706 ms
[Kavita] [2024-03-21 07:21:22.396 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/all-related?seriesId=4 responded 200 in 4.9722 ms
[Kavita] [2024-03-21 07:21:22.415 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/series-detail?seriesId=4 responded 200 in 16.7397 ms
[Kavita] [2024-03-21 07:21:24.332 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /library/1/series/4 responded 304 in 0.6067 ms
[Kavita] [2024-03-21 07:21:24.607 +00:00  30] [Debug] API.Controllers.LibraryController Caching libraries for library_Elry
[Kavita] [2024-03-21 07:21:24.609 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library responded 200 in 2.2067 ms
[Kavita] [2024-03-21 07:21:24.611 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 0.9121 ms
[Kavita] [2024-03-21 07:21:24.614 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/device responded 200 in 0.5727 ms
[Kavita] [2024-03-21 07:21:24.619 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/stream/sidenav?visibleOnly=true responded 200 in 4.1120 ms
[Kavita] [2024-03-21 07:21:24.620 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 0.3305 ms
[Kavita] [2024-03-21 07:21:24.621 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/users/has-library-access?libraryId=1 responded 200 in 0.7053 ms
[Kavita] [2024-03-21 07:21:24.822 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 0.9191 ms
[Kavita] [2024-03-21 07:21:24.827 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme/download-content?themeId=2 responded 200 in 3.5609 ms
[Kavita] [2024-03-21 07:21:24.857 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/metadata?seriesId=4 responded 200 in 2.6442 ms
[Kavita] [2024-03-21 07:21:24.858 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/readinglist/lists-for-series?seriesId=4 responded 200 in 0.6953 ms
[Kavita] [2024-03-21 07:21:24.860 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/has-progress?seriesId=4 responded 200 in 0.5803 ms
[Kavita] [2024-03-21 07:21:24.863 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/continue-point?seriesId=4 responded 200 in 3.2937 ms
[Kavita] [2024-03-21 07:21:24.869 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/4 responded 200 in 5.3912 ms
[Kavita] [2024-03-21 07:21:24.897 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library/type?libraryId=1 responded 200 in 26.8261 ms
[Kavita] [2024-03-21 07:21:24.900 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/want-to-read?seriesId=4 responded 200 in 1.9589 ms
[Kavita] [2024-03-21 07:21:25.059 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/next-expected?seriesId=4 responded 200 in 2.6226 ms
[Kavita] [2024-03-21 07:21:25.105 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/all-related?seriesId=4 responded 200 in 5.5593 ms
[Kavita] [2024-03-21 07:21:25.108 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/metadata/series-detail-plus?seriesId=4&libraryType=0 responded 200 in 2.2722 ms
[Kavita] [2024-03-21 07:21:25.116 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/series-detail?seriesId=4 responded 200 in 7.4054 ms
[Kavita] [2024-03-21 07:21:25.117 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/time-left?seriesId=4 responded 200 in 0.7658 ms
[Kavita] [2024-03-21 07:21:25.118 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/scrobbling/library-allows-scrobbling?seriesId=4 responded 200 in 0.2649 ms
[Kavita] [2024-03-21 07:21:25.119 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/scrobbling/has-hold?seriesId=4 responded 200 in 0.2337 ms
[Kavita] [2024-03-21 07:21:25.120 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/rating/overall?seriesId=4 responded 200 in 1.3373 ms
[Kavita] [2024-03-21 07:21:25.530 +00:00  34] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 918.9967 ms
[Kavita] [2024-03-21 07:21:26.647 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 920.4296 ms
```

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by ghost**
# Fixed
- Fixed: Fixed an issue where uploading a custom cover wasn't respecting Cover Size setting (Fixes #2807)

### CODE REVIEW

File: API/Controllers/UploadController.cs [hunk 1]
```diff
@@ -225,17 +227,13 @@ public async Task<ActionResult> UploadReadingListCoverImageFromUrl(UploadFileDto
...
-        if (thumbnailSize > 0)
-        {
-            return _imageService.CreateThumbnailFromBase64(uploadFileDto.Url,
-                filename, encodeFormat, thumbnailSize);
-        }
-
+        var settings = await _unitOfWork.SettingsRepository.GetSettingsDtoAsync();
+        var encodeFormat = settings.EncodeMediaAs;
+        var coverImageSize = settings.CoverImageSize;
         return _imageService.CreateThumbnailFromBase64(uploadFileDto.Url,
```
Comment (majora2007) [inline API/Controllers/UploadController.cs:236]: Please have a newline before a return statement.

Comment (ghost) [reply API/Controllers/UploadController.cs:236]: > Please have a newline before a return statement.

I just found out the size is not fixed, but somehow its still low res, it just blows up the low res into a bigger size, i need to have a second look.
