### PR TITLE
EPUB Reader Fixes

### LINKED ISSUE #3330: Using nav menu arrow button to go to "next chapter" on epub doesn't scroll to top
### What happened?

When reading epubs on the computer, if scrolled down to the bottom of a chapter, using the "next chapter" button / arrow at the top right takes you to the next chapter, but scrolled down the same amount / page length. (Doesn't scroll back up to start of the chapter).

### What did you expect?

Expected it to scroll to top of the new chapter, as when navigating using the arrow keys.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Additional Notes

_No response_

### LINKED ISSUE #3586: Epub reader; Last page shown twice in double page mode
### What happened?

In double reader mode, the Epub reader always displays the last page of a section on the right. This means that the second to last page is displayed right and then left, when the total number of pages in the section is uneven.

### What did you expect?

I expected the epub reading to add an empty page, to keep pages from being displayed twice

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Mac

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Additional Notes

I'll have a look into this myself later this week :)

### PR DESCRIPTION
**Pull request by Fesaa**
# Changed
- Changed: When reading in Double Column mode, Kavita will now prevent seeing the same text twice by added an empty page when needed (Closes #3586)

# Fixed
- Fixed: Fixed chapter not always scrolling to the top. Was not able to reproduce but used a community fed fix. (Thanks @joonhuiwong) (Fixes #3330)

### CODE REVIEW

File: UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts [hunk 1]
```diff
@@ -1069,6 +1080,28 @@ export class BookReaderComponent implements OnInit, AfterViewInit, OnDestroy {
...
+  private addEmptyPageIfRequired(): void {
+    if (this.layoutMode !== BookPageLayoutMode.Column2 || this.isSingleImagePage) {
+      return;
+    }
+
+    const [,, pageWidth] = this.getVirtualPage();
+    const actualWidth = this.bookContentElemRef.nativeElement.scrollWidth;
+    const lastPageWidth = actualWidth % pageWidth;
+
+    if (lastPageWidth >= pageWidth/2 || lastPageWidth === 0) {
```
Comment (majora2007) [inline UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts]: `pageWidth / 2` please

File: UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts [hunk 2]
```diff
@@ -1069,6 +1080,28 @@ export class BookReaderComponent implements OnInit, AfterViewInit, OnDestroy {
...
+      // The last page needs more than one column, no pages will be duplicated
+      return;
+    }
+
+    // Need to adjust height with the column gap to ensure we don't have too much extra page
+    const columnHeight = this.getPageHeight()-COLUMN_GAP;
+    const emptyPage = this.renderer.createElement('div');
+    this.renderer.setStyle(emptyPage, 'height', columnHeight + 'px');
```
Comment (majora2007) [inline UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts:1101]: Newline above this to separate the flow of the code

File: UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts [hunk 3]
```diff
@@ -1069,6 +1080,28 @@ export class BookReaderComponent implements OnInit, AfterViewInit, OnDestroy {
...
+    const actualWidth = this.bookContentElemRef.nativeElement.scrollWidth;
+    const lastPageWidth = actualWidth % pageWidth;
+
+    if (lastPageWidth >= pageWidth/2 || lastPageWidth === 0) {
+      // The last page needs more than one column, no pages will be duplicated
+      return;
+    }
+
+    // Need to adjust height with the column gap to ensure we don't have too much extra page
+    const columnHeight = this.getPageHeight()-COLUMN_GAP;
```
Comment (majora2007) [inline UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts]: Spaces around the operator. This helps with reading the code.

**Review by majora2007 — CHANGES_REQUESTED** [review]
Overall code and comments look good.

**Review by majora2007 — APPROVED** [review]
